ergonode/frontend

- store/alerts/actions.js
- retrieved custom duration time in alerts
> ERG-#26 - retrieved custom duration time in alerts

- store/data/actions.js
- store/data/mutations.js
- store/index.js
- refactored data store module
> Pr26 - refactored data store module

- defaults/grid/cookies.js
- store/grid/actions.js
- store/grid/mutations.js
- store/index.js
- pull out mutation types to constants
- unified mutations / actions method declarations
- improve code readability in grid actions
> Pr26 - grid module refactored

- core/components/SideBar/SideBar.vue
- core/components/SideBar/SideBarListElement.vue
- core/components/SideBar/SideBarListGroup.vue
- core/components/SideBar/SideBarListGroupElement.vue
- core/components/Transitions/FadeSideBarTextTransition.vue
> SideBar improvement

- modules/@ergo/core/components/Grid/Grid.vue
- modules/@ergo/core/components/Grid/Header/GridHeader.vue
- modules/@ergo/core/components/Grid/Modals/GridSettingsModalForm.vue
Add missing configuration to Grid.
- [ x I have read the contribution requirements and fulfil them.
> feature(grid) add missing collection layout configuration

- modules/@ergo/core/components/Grid/Layout/Collection/Cells/GridCollectionCell.vue
- modules/@ergo/core/components/Grid/Layout/Collection/GridCollectionLayout.vue
- modules/@ergo/core/components/Multimedia/Picture.vue
- modules/@ergo/core/defaults/grid/index.js
- modules/@ergo/products/components/Tabs/ProductGridTab.vue
Collection layout had wrong height - it was stretching height of cells
> Collection layout settings

- modules/@ergo/core/components/Grid/Layout/Collection/Cells/GridCollectionCell.vue
- modules/@ergo/core/components/Multimedia/Picture.vue
Added: 
- Config for **Picture**
Fixed:
- horizontal scroll
- stretched cells horizontally
Issue # (#374 )
> Grid collection layout responsive layout

- modules/@ergo/attributes/components/Tabs/List/AttributesListTab.vue
- modules/@ergo/attributes/components/Tabs/List/SystemAttributesListTab.vue
- modules/@ergo/category-trees/components/Tabs/List/CategoriesListTab.vue
- modules/@ergo/category-trees/store/tree/actions.js
- modules/@ergo/core/components/Tabs/List/LanguagesListTab.vue
- modules/@ergo/core/mixins/list/fetchListDataMixin.js
- modules/@ergo/core/mixins/list/fetchListGroupDataMixin.js
- modules/@ergo/core/services/list/getList.service.js
- modules/@ergo/products/components/Forms/RestoreForm.vue
- modules/@ergo/products/components/Modals/RestoreAttributeParentModalForm.vue
- modules/@ergo/products/services/deleteAttributeValue.service.js
- Added caching mechanism for every list in application
- Changed the way we restore language values for product template.
Issue # (#466)
> feature(product) add caching algorithm for lists

- modules/@ergo/collections/services/createCollection.service.js
- modules/@ergo/core/components/Grid/AdvancedFilters/Contents/GridAdvancedFilterMultiselectContent.vue
- modules/@ergo/core/components/Grid/AdvancedFilters/Contents/GridAdvancedFilterSelectContent.vue
- modules/@ergo/core/components/Grid/AdvancedFilters/DropDown/AdvancedFilterDropDown.vue
- modules/@ergo/core/components/Grid/AdvancedFilters/GridAdvancedFiltersRemoveAllButton.vue
- modules/@ergo/core/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergo/core/components/Modal/ModalForm.vue
- modules/@ergo/core/mixins/grid/fetchGridDataMixin.js
- modules/@ergo/products/pages/catalog/_product/_id.vue
Fixes:
- Create collection parsing data 
- Advanced Select/MultiSelect filter DropDown
- Grid fetching data
- Modal header style
- Remove all filters button style
> bugfix(core) bug fixes

- modules/@ergo/collections/components/Tabs/CollectionProductsTab.vue
- modules/@ergo/core/components/Grid/Layout/Collection/Cells/GridCollectionCell.vue
- modules/@ergo/core/components/Grid/Layout/Table/Cells/Presentation/GridSelectPresentationCell.vue
- modules/@ergo/product-templates/pages/product-templates/_template/_id.vue
- modules/@ergo/product-templates/services/createProductTemplate.service.js
- modules/@ergo/product-templates/store/templateDesigner/actions.js
- modules/@ergo/products/components/ProductCollection/ProductCollectionItem.vue
- modules/@ergo/products/components/Tabs/ProductGridTab.vue
- Removed fab from GridCollectionCell and replaced the action to clickable whole cell
- Renamed default text and image for product request
Issue # (#418)
> Grid collection layout improvement

- .storybook/reset-storybook.scss
- modules/@ergo/attributes/components/Forms/AttributeForm.vue
- modules/@ergo/attributes/models/__tests__/attributeTypes.test.js
- modules/@ergo/attributes/models/attributeTypes.js
- modules/@ergo/attributes/pages/attributes/_attribute/_id.vue
- modules/@ergo/attributes/services/createAttribute.service.js
- modules/@ergo/attributes/store/attribute/actions.js
- modules/@ergo/core/assets/scss/input/input.scss
- modules/@ergo/core/assets/scss/reset.scss
- modules/@ergo/core/components/Alerts/__tests__/FlashMessage.test.js
- modules/@ergo/core/components/Buttons/Fab.vue
- modules/@ergo/core/components/Grid/Layout/Table/Cells/Data/GridTextAreaDataCell.vue
- modules/@ergo/core/components/Grid/Layout/Table/Cells/Edit/GridTextAreaEditCell.vue
- modules/@ergo/core/components/Inputs/RichTextEditor/Button/RichTextEditorButton.vue
- modules/@ergo/core/components/Inputs/RichTextEditor/MenuBubble/RichTextEditorMenuBubble.vue
- modules/@ergo/core/components/Inputs/RichTextEditor/RichTextEditor.vue
- modules/@ergo/core/components/TemplateGrid/__tests__/TemplateGridHeader.test.js
- modules/@ergo/core/mixins/page/categoryManagementPageMixin.js
- modules/@ergo/product-templates/components/Tabs/TemplateDesignerTab.vue
- modules/@ergo/products/components/Forms/Fields/ProductTemplateFormTextAreaField.vue
To TextArea attribute added flag which will determinate if attribute will be presented as RichTextEditor or TextArea.
Issue # (#428)
> Integarte rte with attributes

- modules/@ergo/products/components/Forms/Fields/ProductTemplateFormTextAreaField.vue
Swap method call of updating product draft value.
Issue # (#428 )
> bugfix(product) #428 swap method call

- modules/@ergo/core/components/Tabs/UnitsSettingsGridTab.vue
- modules/@ergo/products/components/Grid/Layout/Table/Cells/GridAttachedDataCell.vue
- modules/@ergo/products/components/Tabs/ProductGroupTab.vue
- modules/@ergo/products/components/Tabs/ProductVariantsTab.vue
- fixed displayed removed units in attribute unit creation
- fixed not refreshed attached grid column cell values on product group tab
> Release 0.9 bug fixes

- CHANGELOG.md
- README.md
- package.json
- feature [#384](https://github.com/ergonode/frontend/issues/384) Product variants
- feature [#418](https://github.com/ergonode/frontend/issues/418) GridCollectionLayout for product related Grid's
- feature [#428](https://github.com/ergonode/frontend/issues/428) Integrate TextArea/RTE
- feature [#430](https://github.com/ergonode/frontend/issues/430) Optimisation for D&D at Grid and AdvancedFilters
- feature dependencies update
- perf - Language inheritance communication
- bugfix - Product template updating draft values
> Release 0.9.0

- .storybook/reset-storybook.scss
- modules/@ergo/core/assets/scss/reset.scss
- modules/@ergo/core/components/Grid/AdvancedFilters/GridAdvancedFilters.vue
- modules/@ergo/core/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergo/core/components/Modals/ConfirmModal.vue
- modules/@ergo/products/components/Modals/RestoreAttributeParentModalConfirm.vue
- Add missing reset css rules
- Fixed draggable list element disable state
Issue # (#453)
> bugfix(core): draggable disable list, reset css (#453)

- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaForm.vue
- modules/@ergonode/core/src/components/Inputs/CheckBox.vue
- modules/@ergonode/core/src/components/SideBar/SideBar.vue
- modules/@ergonode/core/src/components/SideBar/SideBarListGroup.vue
- modules/@ergonode/core/src/components/TabBar/VerticalTabBar.vue
- modules/@ergonode/core/src/components/TabBar/VerticalTabBarList.vue
- modules/@ergonode/core/src/components/TemplateGrid/TemplateGridWrapper.vue
- modules/@ergonode/core/src/components/Transitions/AutoHeightTransition.vue
- modules/@ergonode/core/src/components/Transitions/AutoWidthTransition.vue
- modules/@ergonode/import/src/components/Tabs/ImportProfileSettingsTab.vue
- modules/@ergonode/products/src/pages/catalog/_product/_id.vue
- modules/@ergonode/products/src/store/product/actions.js
- Applying draft from product page wasn't sent.
- Added animation component - auto width / height.
Issue # (#411)
> bugfix(multimedia): applu draft, animation (#411)

- modules/@ergonode/dashboard/src/assets/images/add_category.svg
- modules/@ergonode/dashboard/src/assets/images/add_template.svg
- modules/@ergonode/dashboard/src/components/SimpleGrid/SimpleGrid.vue
- modules/@ergonode/dashboard/src/pages/dashboard/index.vue
> rebase dashboard

- modules/@ergonode/core/src/components/Multimedia/Picture.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
Replace endpoint for image presentation
Issue # (#411)
> Media thumbnail

- .storybook/main.js
> feature(storybook): alias update

- modules/@ergonode/category-trees/src/components/Forms/CategoryTreeForm.vue
- modules/@ergonode/channels/src/services/createChannel.service.js
- modules/@ergonode/core/src/components/Form/Form.vue
> bugfix(core): form validation, misspelling

- modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
- modules/@ergonode/channels/src/pages/channels/_channel/_id.vue
- modules/@ergonode/channels/src/services/createChannel.service.js
- modules/@ergonode/channels/src/store/channels/actions.js
- modules/@ergonode/channels/src/store/channels/state.js
- modules/@ergonode/core/src/components/Form/FormErrorLabel.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormArrayObject.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormArrayString.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormObject.vue
Fix validation on channel form. 
> bugfix(channel): channel name validation

- modules/@ergonode/media/src/pages/media/_resource/_id.vue
- modules/@ergonode/media/src/store/media/actions.js
> bugfix(media): fix wrong media name

- modules/@ergonode/attributes/src/components/Forms/AttributeForm.vue
- modules/@ergonode/attributes/src/components/Forms/AttributeGroupForm.vue
- modules/@ergonode/categories/src/components/Forms/CategoryForm.vue
- modules/@ergonode/category-trees/src/components/Forms/CategoryTreeForm.vue
- modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
- modules/@ergonode/collections/src/components/Forms/CollectionForm.vue
- modules/@ergonode/core/src/components/Forms/UnitForm.vue
- modules/@ergonode/media/src/pages/media/_resource/_id.vue
- modules/@ergonode/media/src/store/media/actions.js
- modules/@ergonode/product-statuses/src/components/Form/ProductStatusForm.vue
- modules/@ergonode/segments/src/components/Forms/SegmentForm.vue
- modules/@ergonode/users/src/components/Pages/UserPage.vue
- modules/@ergonode/users/src/components/Pages/UserRolesPage.vue
- modules/@ergonode/users/src/components/Tabs/RolePrivilegesTab.vue
- modules/@ergonode/users/src/components/Tabs/UserLanguageRestrictionsTab.vue
> Bug fixes v0.10

- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormArrayObject.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
- modules/@ergonode/media/src/components/Modal/ModalMediaTabBar.vue
> Bigfixes - modal / JSON Schema form

- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
- modules/@ergonode/channels/src/components/Tabs/ChannelSchedulerTab.vue
- modules/@ergonode/channels/src/config/imports.js
- modules/@ergonode/channels/src/config/routes.js
- modules/@ergonode/channels/src/pages/channels/_channel/_id.vue
- modules/@ergonode/channels/src/store/channels/actions.js
- modules/@ergonode/channels/src/store/channels/state.js
- modules/@ergonode/core/src/models/calendar/calendar.js
New tab on channel page with scheduler configuration 
> feature(channel): tab with scheduler configuration

- modules/@ergonode/attributes/src/components/Forms/AttributeForm.vue
- modules/@ergonode/attributes/src/components/Forms/AttributeGroupForm.vue
- modules/@ergonode/attributes/src/components/Tabs/List/AttributesListTab.vue
- modules/@ergonode/categories/src/components/Forms/CategoryForm.vue
- modules/@ergonode/category-trees/src/components/Forms/CategoryTreeForm.vue
- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
- modules/@ergonode/collections/src/components/Forms/CollectionForm.vue
- modules/@ergonode/conditions/src/components/Lists/ConditionsListElement.vue
- modules/@ergonode/conditions/src/components/Tabs/Lists/ConditionsListTab.vue
- modules/@ergonode/core/src/components/Forms/MainSettingsForm.vue
- modules/@ergonode/core/src/components/Inputs/RadioButton.vue
- modules/@ergonode/core/src/pages/login/index.vue
- modules/@ergonode/import/src/components/Forms/ImportProfileForm.vue
- modules/@ergonode/media/src/components/Buttons/LinkRelationButton.vue
- modules/@ergonode/product-statuses/src/components/Form/ProductStatusForm.vue
- modules/@ergonode/product-templates/src/components/Forms/TemplateDesignerForm.vue
- modules/@ergonode/products/src/components/Form/ProductForm.vue
- modules/@ergonode/products/src/components/Form/RestoreForm.vue
- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
- modules/@ergonode/segments/src/components/Forms/SegmentForm.vue
- modules/@ergonode/segments/src/components/Tabs/ConditionSetDesignTab.vue
- modules/@ergonode/status-transitions/src/components/Forms/TransitionForm.vue
- modules/@ergonode/status-transitions/src/components/Pages/TransitionPage.vue
- modules/@ergonode/status-transitions/src/components/Tabs/ConditionSetDesignTab.vue
- modules/@ergonode/users/src/components/Forms/UserForm.vue
- modules/@ergonode/users/src/components/Forms/UserRoleForm.vue
Form disabled field related with privileges.
> Bugfix/release 0.10.0

- modules/@ergonode/collections/src/components/Tabs/CollectionProductsTab.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridLabelDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridMultiSelectDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridSelectDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Edit/GridMultiSelectEditCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Edit/GridSelectEditCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/core/src/components/Inputs/RichTextEditor/RichTextEditor.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/products/src/components/Form/Field/ProductTemplateFormImageField.vue
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/products/src/components/Tabs/ProductGroupTab.vue
- modules/@ergonode/products/src/components/Tabs/ProductVariantsTab.vue
- package-lock.json
- package.json
- Fix of language code at Grid for few cells
- RTE was not displaying styles
- Image wasn't scaling well at product page
> bugfix(release): language code

- modules/@ergonode/core/src/components/Form/Form.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
- modules/@ergonode/core/src/components/Form/Subsection/FormSubsection.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
- Add require mark for subsections at forms
- Add filenames instead of UUID's at FileUploaders
> bugfix(release): filename at file uploader, JSON schema validation

- modules/@ergonode/media/src/components/Tabs/UploadFileTab.vue
> bugfix(multimedia): remove language from url

- modules/@ergonode/attributes/src/components/Tabs/AttributeGridTab.vue
- modules/@ergonode/attributes/src/components/Tabs/AttributeGroupGridTab.vue
- modules/@ergonode/categories/src/components/Tabs/CategoryGridTab.vue
- modules/@ergonode/category-trees/src/components/Tabs/CategoryTreesGridTab.vue
- modules/@ergonode/channels/src/components/Modals/ExportDetailsModalGrid.vue
- modules/@ergonode/channels/src/components/Tabs/ChannelGridTab.vue
- modules/@ergonode/collections/src/components/Tabs/CollectionGridTab.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormTableRowWidget.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
- modules/@ergonode/core/src/components/Multimedia/UserFabAvatar.vue
- modules/@ergonode/core/src/components/Tabs/UnitsSettingsGridTab.vue
- modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
- modules/@ergonode/import/src/components/Tabs/ImportProfileGridTab.vue
- modules/@ergonode/media/src/components/Grid/MediaGrid.vue
- modules/@ergonode/media/src/components/Tabs/MediaGridTab.vue
- modules/@ergonode/product-statuses/src/components/Tabs/ProductStatusGridTab.vue
- modules/@ergonode/product-templates/src/components/Forms/TemplateDesignerForm.vue
- modules/@ergonode/product-templates/src/pages/product-templates/index.vue
- modules/@ergonode/product-templates/src/store/productTemplate/state.js
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/segments/src/components/Tabs/SegmentsGridTab.vue
- modules/@ergonode/status-transitions/src/components/Tabs/TransitionsGridTab.vue
- modules/@ergonode/users/src/components/Inputs/UploadAvatar.vue
- modules/@ergonode/users/src/components/Tabs/RolesGridTab.vue
- modules/@ergonode/users/src/components/Tabs/UsersGridTab.vue
- add missing language to avatar request
- add missing language to product status request
- improve styling for json schema row
- add support for preview row actions
> bugfix(release): missing language in url, clean code, style improvement

- modules/@ergonode/category-trees/src/store/categoryTree/actions.js
- modules/@ergonode/core/src/components/Forms/UnitForm.vue
- modules/@ergonode/users/src/components/Forms/UserRoleForm.vue
Add missing hints for UnitForm
Fix crash of categories list at category tree
> bugfix(core): add missing hint, add missing language code

- modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
- modules/@ergonode/channels/src/components/Pages/ChannelPage.vue
- modules/@ergonode/channels/src/services/index.js
- modules/@ergonode/channels/src/store/channel/actions.js
- modules/@ergonode/collections/src/components/Modals/AddProductsBySKUModalForm.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormString.vue
- modules/@ergonode/core/src/components/Form/JSONSchemaForm/JSONSchemaFormTableRowWidget.vue
- modules/@ergonode/core/src/components/Multimedia/Picture.vue
- modules/@ergonode/media/src/components/Grid/MediaGrid.vue
- modules/@ergonode/notifications/src/components/List/NotificationsListElement.vue
- modules/@ergonode/products/src/components/Grid/Layout/Table/Cells/GridProductAttachDataCell.vue
- modules/@ergonode/products/src/components/Modals/AddProductsBySKUModalForm.vue
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/segments/src/components/Modals/Collection/AddProductsFromSegmentModalForm.vue
- modules/@ergonode/segments/src/components/Modals/Product/AddProductsFromSegmentModalForm.vue
- modules/@ergonode/users/src/components/Forms/UserAvatarForm.vue
- modules/@ergonode/users/src/components/Forms/UserRoleForm.vue
- modules/@ergonode/users/src/store/role/actions.js
> Validations imporvement

- cypress/integration/1_attribute/2_addAttribute.feature
- modules/@ergonode/attributes/src/locales/en.json
- modules/@ergonode/core/src/mixins/list/fetchListDataMixin.js
- modules/@ergonode/media/src/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
> bugfix(core): stabilisation

- modules/@ergonode/attributes/src/components/Tabs/List/SystemAttributesListTab.vue
- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/attributes/src/extends/methods/attribute.js
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Edit/GridImageEditCell.vue
- modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
- modules/@ergonode/core/src/defaults/grid/index.js
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormDateField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormMultiSelectField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormNumericField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormPriceField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormSelectField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormTextAreaField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormTextField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormUnitField.vue
- modules/@ergonode/products/src/components/Modals/RestoreAttributeParentConfirmModal.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsFromListModalGrid.vue
- modules/@ergonode/products/src/services/index.js
- modules/@ergonode/products/src/store/product/actions.js
> bugfix(core): release stabilisation

- modules/@ergonode/products/src/components/Widgets/CompletenessWidget.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsFromListModalGrid.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductGroupTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
> Grid links

- modules/@ergonode/core/src/components/Grid/AdvancedFilters/GridAdvancedFilters.vue
- modules/@ergonode/core/src/components/Grid/Grid.vue
- modules/@ergonode/core/src/components/Grid/Header/GridHeader.vue
- modules/@ergonode/core/src/mixins/grid/fetchGridDataMixin.js
- modules/@ergonode/core/src/models/mappers/errorsMapper.js
- modules/@ergonode/core/src/models/navigation/navigationBarUserMenu.js
- modules/@ergonode/notifications/src/services/index.js
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
- Removing advanced filters fixes
- Translations mapper for errors
> bugfix(core): advanced filter stabilisation

- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridBoolDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridCheckDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridFileDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridGalleryDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridIntegerDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridMultiSelectDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/Cells/Data/GridNumericDataCell.vue
- modules/@ergonode/core/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/core/src/mixins/grid/cell/gridDataCellMixin.js
- modules/@ergonode/core/src/mixins/grid/cell/gridResizerCellMixin.js
- modules/@ergonode/core/src/mixins/grid/fetchAdvancedFiltersDataMixin.js
- modules/@ergonode/notifications/src/services/index.js
- Improved draft validation
- Fixed notification request
> bugfix(core): grid draft improvement

- modules/@ergonode/notifications/src/components/List/NotificationsListElement.vue
Notifications date format change
> fix date format

- modules/@ergonode/attributes/src/components/Forms/AttributeForm.vue
- modules/@ergonode/attributes/src/store/attributeGroup/actions.js
- modules/@ergonode/categories/src/extends/components/Forms/ProductFormCategory.vue
- modules/@ergonode/categories/src/store/category/actions.js
- modules/@ergonode/core/src/components/Autocomplete/Autocomplete.vue
- modules/@ergonode/core/src/components/Forms/MainSettingsForm.vue
- modules/@ergonode/core/src/components/Select/DropDown/DropDownListSearch.vue
- modules/@ergonode/core/src/components/Tabs/MainSettingsTab.vue
- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
- modules/@ergonode/products/src/components/Forms/ProductForm.vue
- modules/@ergonode/status-transitions/src/components/Forms/TransitionForm.vue
- modules/@ergonode/users/src/components/Forms/UserForm.vue
- modules/@ergonode/users/src/store/role/actions.js
Added `Autocomplete` component which is designed for lazy loading dropdown's and searching within their options
> feature(core): integrate autocomplete

- modules/@ergonode/core/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductGroupTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
> bugfix(product): improve product with variant filter

- modules/@ergonode/categories/src/config/extends.js
- modules/@ergonode/collections/src/components/ProductCollection/ProductCollectionItem.vue
- modules/@ergonode/media/src/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
- modules/@ergonode/media/src/components/Grid/MediaGrid.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/products/src/extends/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
- modules/@ergonode/users/src/components/Inputs/UploadAvatar.vue
Product form - sending category error.
> bugfix(product): extend category on product form

- modules/@ergonode/media/src/components/Grid/MediaGrid.vue
- modules/@ergonode/product-statuses/src/components/Widgets/StatusesWidget.vue
- modules/@ergonode/products/src/extends/components/Grid/Layout/Table/Cells/Presentation/GridLabelPresentationCell.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductGroupTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
Improved product type stabilisation
> Product type stabilisation

- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Presentation/GridImagePresentationCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridActionColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridRowActionColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridSelectRowColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Improve logic of action columns.
> Implement select row column

- modules/@ergonode/ui/src/components/Grid/Buttons/MassActionButton.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridDraggableDataColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Added support for mass actions inside Grid. The mass actions must be defined out of Grid scope.
> feature(core): Add mass action handler for Grid

- modules/@ergonode/comments/src/components/Comments/CommentPresentation.vue
- modules/@ergonode/core/src/defaults/theme/index.js
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFile.vue
- modules/@ergonode/products/src/store/product/actions.js
- modules/@ergonode/ui/src/assets/scss/_variables/_elevators.scss
- modules/@ergonode/ui/src/components/Button/Button.vue
- modules/@ergonode/ui/src/components/Fab/Fab.vue
- modules/@ergonode/ui/src/components/IconButton/IconButton.vue
Add destructive theme to button kind components
> Destructive theme

- modules/@ergonode/categories/src/extends/store/product/state.js
- modules/@ergonode/products/src/components/Forms/ProductForm.vue
- modules/@ergonode/products/src/components/Forms/ProductTemplateForm.vue
- modules/@ergonode/products/src/components/Progress/ProductCompleteness.vue
- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
- modules/@ergonode/products/src/store/product/state.js
- modules/@ergonode/ui/src/components/Button/Button.vue
- modules/@ergonode/ui/src/components/Events/IntersectionObserver.vue
> Support for change product template

- modules/@ergonode/ui/src/mixins/grid/gridResizerCellMixin.js
> Add missing variable

- modules/@ergonode/ui/src/components/ConfirmModal/ConfirmModal.vue
- modules/@ergonode/ui/src/components/ConfirmModal/ConfirmModalHeader.vue
> Add type prop to modal

- modules/@ergonode/category-trees/src/components/Tabs/List/CategoriesListTab.vue
- modules/@ergonode/ui/src/components/Select/Select.vue
- package-lock.json
- package.json
> search language for categories, update virtualizing dependencie

- modules/@ergonode/products/src/extends/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
- modules/@ergonode/ui/src/components/Autocomplete/Autocomplete.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridSelectRowColumn.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
- package-lock.json
- package.json
> Update DOm vierualization dependency

- modules/@ergonode/channels/src/components/Modals/ExportDetailsModalGrid.vue
- modules/@ergonode/core/src/mixins/grid/fetchGridDataMixin.js
- modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
- modules/@ergonode/media/src/components/Grid/MediaGrid.vue
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductGroupTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
> Add missing limit param

- .env.dist
- modules/@ergonode/attributes/src/services/attribute/index.js
- modules/@ergonode/categories/src/services/index.js
- modules/@ergonode/category-trees/src/models/__tests__/__mocks__/categories.mock.js
- modules/@ergonode/category-trees/src/models/treeMapper.js
- modules/@ergonode/category-trees/src/store/categoryTree/actions.js
- modules/@ergonode/channels/src/components/Modals/ExportDetailsModalGrid.vue
- modules/@ergonode/collections/src/components/Tabs/CollectionProductsTab.vue
- modules/@ergonode/conditions/src/components/ConditionSetDesigner/ConditionSetItem.vue
- modules/@ergonode/core/src/defaults/grid/index.js
- modules/@ergonode/core/src/mixins/grid/fetchGridDataMixin.js
- modules/@ergonode/core/src/mixins/list/fetchListGroupDataMixin.js
- modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
- modules/@ergonode/media/src/components/Grid/MediaGrid.vue
- modules/@ergonode/product-templates/src/models/templateMapper.js
- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsFromListModalGrid.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductGroupTab.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
> Grid memory leak fix

- layouts/default.vue
- modules/@ergonode/attributes/src/components/Modals/CreateAttributeModalForm.vue
- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/attributes/src/pages/attributes/_attribute/_id.vue
- modules/@ergonode/authentication/src/store/authentication/actions.js
- modules/@ergonode/channels/src/components/Modals/CreateChannelModalForm.vue
- modules/@ergonode/channels/src/config/extends.js
- modules/@ergonode/channels/src/pages/channels/_channel/_id.vue
- modules/@ergonode/core/src/components/Buttons/RemoveUnitButton.vue
- modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
- modules/@ergonode/core/src/components/Tabs/UnitGeneralTab.vue
- modules/@ergonode/core/src/components/Tabs/UnitsSettingsGridTab.vue
- modules/@ergonode/core/src/config/extends.js
- modules/@ergonode/core/src/services/dictionary/index.js
- modules/@ergonode/core/src/store/dictionaries/actions.js
- modules/@ergonode/core/src/store/dictionaries/state.js
- modules/@ergonode/import/src/components/Modals/CreateImportProfileModalForm.vue
- modules/@ergonode/import/src/config/extends.js
- modules/@ergonode/products/src/components/Modals/CreateProductModalForm.vue
- modules/@ergonode/products/src/config/extends.js
- modules/@ergonode/products/src/pages/catalog/_product/_id.vue
- modules/@ergonode/ui/src/components/Grid/AdvancedFilters/Type/GridUnitTypeAdvancedFilter.vue
- modules/@ergonode/users/src/components/Tabs/RolePrivilegesTab.vue
- modules/@ergonode/users/src/components/Tabs/UserPrivilegesGridTab.vue
- modules/@ergonode/users/src/config/extends.js
- store/index.js
> feature(core): added async dictionaries

- modules/@ergonode/core/src/components/TemplateGrid/TemplateGridContainer.vue
> Designer height

- modules/@ergonode/core/src/components/TemplateGrid/TemplateGridContainer.vue
- modules/@ergonode/core/src/defaults/list/index.js
> Designer height and not assigned group id

- modules/@ergonode/core/src/locales/en_GB.json
Translation JSON file - bugfix
> bugfix(core): translation JSON file

- modules/@ergonode/categories/src/components/Selects/CategorySelect.vue
- modules/@ergonode/categories/src/locales/en_GB.json
- modules/@ergonode/category-trees/src/locales/en_GB.json
- modules/@ergonode/core/src/mixins/list/fetchListGroupDataMixin.js
- modules/@ergonode/core/src/models/arrayWrapper.js
- modules/@ergonode/ui/src/components/CheckBox/CheckBox.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Buttons/ClearSearchButton.vue
- modules/@ergonode/ui/src/components/SelectList/SelectList.vue
- modules/@ergonode/ui/src/components/SelectList/SelectListElement.vue
- modules/@ergonode/ui/src/components/Toggler/Toggler.vue
- modules/@ergonode/ui/src/components/TreeAccordion/TreeAccordionItem.vue
- package-lock.json
- package.json
- Improved displaying placeholders
- Improved selection of multiselects
- Fixed not displaying not asssigned attributes
> Category select imporvement

- modules/@ergonode/attributes/src/extends/components/Forms/ProductTemplateFormPresentation.vue
- modules/@ergonode/category-trees/src/components/AdvancedFilters/Type/AdvancedFilterCategoryTreeType.vue
- modules/@ergonode/core/src/mixins/list/fetchListGroupDataMixin.js
- modules/@ergonode/ui/src/components/AdvancedFilters/AdvancedFilter.vue
- modules/@ergonode/ui/src/components/Autocomplete/Autocomplete.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
> Dropdown search placeholder, autocomplete params support

- modules/@ergonode/segments/src/components/Pages/SegmentPage.vue
- modules/@ergonode/users/src/components/Buttons/CreateRoleButton.vue
- modules/@ergonode/users/src/components/Buttons/CreateUserButton.vue
- modules/@ergonode/users/src/components/Buttons/RemoveRoleButton.vue
- modules/@ergonode/users/src/components/Buttons/RemoveUserButton.vue
- modules/@ergonode/users/src/components/Forms/UserAvatarForm.vue
- modules/@ergonode/users/src/components/Forms/UserForm.vue
- modules/@ergonode/users/src/components/Forms/UserRoleForm.vue
- modules/@ergonode/users/src/components/Modals/CreateRoleModalForm.vue
- modules/@ergonode/users/src/components/Modals/CreateUserModalForm.vue
- modules/@ergonode/users/src/components/Pages/UserPage.vue
- modules/@ergonode/users/src/components/Pages/UserRolesPage.vue
- modules/@ergonode/users/src/components/Tabs/RoleGeneralTab.vue
- modules/@ergonode/users/src/components/Tabs/RolePrivilegesTab.vue
- modules/@ergonode/users/src/components/Tabs/RolesGridTab.vue
- modules/@ergonode/users/src/components/Tabs/UserAvatarTab.vue
- modules/@ergonode/users/src/components/Tabs/UserGeneralTab.vue
- modules/@ergonode/users/src/components/Tabs/UserLanguageRestrictionsTab.vue
- modules/@ergonode/users/src/components/Tabs/UsersGridTab.vue
- modules/@ergonode/users/src/config/routes.js
- modules/@ergonode/users/src/locales/en_GB.json
- modules/@ergonode/users/src/pages/roles/_role/_id.vue
- modules/@ergonode/users/src/pages/roles/index.vue
- modules/@ergonode/users/src/pages/users/_user/_id.vue
- modules/@ergonode/users/src/pages/users/index.vue
- modules/@ergonode/users/src/store/role/actions.js
- modules/@ergonode/users/src/store/user/actions.js
Bugfix return button in user edit page.
Add translations for user module.
> Bugfix/user edit - return button

- modules/@ergonode/categories/src/components/Selects/CategorySelect.vue
- modules/@ergonode/category-trees/src/components/AdvancedFilters/Type/AdvancedFilterCategoryTreeType.vue
- modules/@ergonode/core/src/mixins/list/fetchListGroupDataMixin.js
- modules/@ergonode/ui/src/components/AdvancedFilters/AdvancedFilter.vue
…ty toggler when no records
Add overflow for category tree filter, disable visibility toggler when no records
> Add overflow for category tree filter

- modules/@ergonode/ui/src/components/TreeAccordion/TreeAccordionItem.vue
Selecting in checkbox wasn't calling input event
> Accordion item selection

- modules/@ergonode/comments/src/components/Comments/CommentPresentation.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/LazyImage/LazyImage.vue
- refactored `LazyImage` request
- add validation for generating user avatar
> Add additional validation for fetching user avatar

- modules/@ergonode/attributes/src/components/SideBars/AttributesSideBar.vue
- modules/@ergonode/attributes/src/components/SideBars/SystemAttributesSideBar.vue
- modules/@ergonode/categories/src/components/SideBars/CategoriesSideBar.vue
- modules/@ergonode/core/src/components/SideBars/LanguagesSideBar.vue
- modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
- modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
- modules/@ergonode/ui/src/components/List/ListSearchHeader.vue
- modules/@ergonode/ui/src/components/List/ListSearchSelectHeader.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
- modules/@ergonode/ui/src/components/SideBar/SideBar.vue
- RTE empty paragraph
- Searching at attributes Sidebars
- Grid media / import details crash
> Release bug fixes beta.7

- package-lock.json
- package.json
The problem wasn't inside code base. Problem was fixed by external dependency update.
> Update vue-windowing dependency

- modules/@ergonode/ui/src/components/Grid/Buttons/BatchActionButton.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
When user select any row, BatchActionButton should be highlighted.
> Add batch action button highlighting state

- modules/@ergonode/attributes/src/pages/attributes/index.vue
- modules/@ergonode/authentication/src/components/Layout/Login.vue
- modules/@ergonode/authentication/src/defaults/cookies.js
- modules/@ergonode/authentication/src/defaults/layout/index.js
- modules/@ergonode/authentication/src/store/authentication/actions.js
- modules/@ergonode/core/src/config/index.js
- modules/@ergonode/core/src/defaults/cookies/index.js
- modules/@ergonode/core/src/plugins/i18n.js
- modules/@ergonode/core/src/store/initial.js
- modules/@ergonode/users/src/components/Buttons/RemoveRoleButton.vue
- modules/@ergonode/users/src/components/Buttons/RemoveUserButton.vue
- modules/@ergonode/users/src/components/Buttons/UpdateLanguageRestrictionsButton.vue
- modules/@ergonode/users/src/components/Buttons/UpdateRolePrivilegesButton.vue
- modules/@ergonode/users/src/components/Tabs/RoleGeneralTab.vue
- modules/@ergonode/users/src/components/Tabs/UserAvatarTab.vue
- modules/@ergonode/users/src/components/Tabs/UserGeneralTab.vue
- nuxt.config.js
Fixed user interface translations flushing after page reload. 
> Flashing interface translation

- modules/@ergonode/import/src/pages/imports/_import/_id.vue
Sources for import profile weren't fetched.
> Add missing fetch initial sources dictionary

- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormSelectField.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
- modules/@ergonode/ui/src/components/Select/Select.vue
…t method on apply
- Improved dropdown position calculations
- Added missing dismiss event on apply click
> Improve dropdown calculation, add missing dismiss event

- modules/@ergonode/attributes/src/components/SideBars/AttributesSideBar.vue
Preventing attribute group duplication after new attribute has been created
> Prevent attribute group duplicate

- modules/@ergonode/attributes/src/components/SideBars/AttributesSideBar.vue
- modules/@ergonode/categories/src/components/SideBars/CategoriesSideBar.vue
- modules/@ergonode/categories/src/locales/en_GB.json
- modules/@ergonode/categories/src/locales/pl_PL.json
Add missing custom placeholder for Categories sidebar
> Sidebar category placeholder

- modules/@ergonode/core/src/components/Icons/Logo/IconLogoName.vue
- modules/@ergonode/ui/src/components/Fab/Fab.vue
- modules/@ergonode/ui/src/components/TextField/TextField.vue
- add support for logo icon bounds
- add support for Fab button type
- remove not needed event listeners form TextField
> Add support for logo bounds, set button type for fab

- modules/@ergonode/core/src/models/mappers/__tests__/__mocks__/index.js
- modules/@ergonode/core/src/models/mappers/__tests__/errorsMapper.test.js
- modules/@ergonode/core/src/models/mappers/errorsMapper.js
- modules/@ergonode/core/src/store/feedback/actions.js
- modules/@ergonode/media/src/components/Tabs/UploadFileTab.vue
- Added unit test for validation errors mappers
- Removed legacy validation errors mapper
- Improved validation logic
> Validation errors mapper along with unit tests

- modules/@ergonode/ui/src/assets/scss/global.scss
- modules/@ergonode/ui/src/assets/scss/main.scss
- modules/@ergonode/ui/src/config/index.js
- Separate scss meta and global styles
- Fix page transition
> Bugfix: separate scss meta and global styles

- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Fixed layout shift when there is no data in Grid
> Grid placeholder layout shift

- modules/@ergonode/ui/src/assets/scss/global.scss
Rebase page transition animation
> Rebase css page transition

- modules/@ergonode/category-trees/src/extends/components/SideBars/CategoryTreesSideBar.vue
- modules/@ergonode/category-trees/src/extends/components/VerticalTabs/CategoryTreesVerticalTab.vue
- modules/@ergonode/ui/src/components/SideBar/SideBar.vue
- package-lock.json
- package.json
- Update dependencies of DOM virtualisation
- Add missing class
> Allow scrolling for Categories in Sidebar

- modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
- modules/@ergonode/core/src/components/SideBars/LanguageSideBarElement.vue
- modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
- modules/@ergonode/ui/src/components/Designer/Designer.vue
- modules/@ergonode/ui/src/components/TreeDesigner/TreeDesignerDraggableLayer.vue
- modules/@ergonode/ui/src/models/mouse/index.js
> Tree designer bugs

- modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItemParameters.vue
- modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
- modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
- modules/@ergonode/ui/src/components/Designer/Designer.vue
- modules/@ergonode/ui/src/components/TreeDesigner/TreeDesignerDraggableLayer.vue
> Designers stabilisation - FF

- modules/@ergonode/categories/src/components/Buttons/CreateCategoryButton.vue
- modules/@ergonode/categories/src/components/Buttons/CreateCategoryFab.vue
- modules/@ergonode/categories/src/components/Modals/CreateCategoryModalForm.vue
- modules/@ergonode/categories/src/components/Selects/CategorySelect.vue
- modules/@ergonode/category-trees/src/components/Buttons/CreateCategoryTreeButton.vue
- modules/@ergonode/category-trees/src/components/Grids/CategoryTreesGrid.vue
- modules/@ergonode/category-trees/src/extends/product/components/SideBars/CategoryTreeSideBarGroupElement.vue
- modules/@ergonode/category-trees/src/extends/product/components/SideBars/CategoryTreesSideBar.vue
- modules/@ergonode/category-trees/src/locales/en_GB.json
- modules/@ergonode/category-trees/src/locales/pl_PL.json
- modules/@ergonode/category-trees/src/models/treeMapper.js
- modules/@ergonode/category-trees/src/pages/category-trees/_tree/_id.vue
- modules/@ergonode/category-trees/src/pages/category-trees/index.vue
- modules/@ergonode/category-trees/src/store/categoryTree/actions.js
> Filter by not assigned categories

- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
- modules/@ergonode/ui/src/components/Paragraph/Paragraph.vue
Fix scheduler form structure and add information paragraph about scheduler time.
Add disables state for fields when `active = false`
Extending the `Paragraph` component by append and prepend slots.
Issue #693 
> bugfix(channel): change scheduler form

- modules/@ergonode/products/src/components/BatchActions/ProductsBatchActions.vue
- modules/@ergonode/products/src/components/Buttons/CreateProductButton.vue
- modules/@ergonode/products/src/components/Buttons/ProductWorkflowActionButton.vue
- modules/@ergonode/products/src/components/Buttons/RemoveProductButton.vue
- modules/@ergonode/products/src/components/Buttons/RestoreProductButton.vue
- modules/@ergonode/products/src/components/Forms/RestoreForm.vue
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/products/src/components/Modals/CreateProductModalForm.vue
- modules/@ergonode/products/src/components/Modals/RestoreAttributeParentConfirmModal.vue
- modules/@ergonode/products/src/components/Modals/RestoreProductAttributesModalForm.vue
- modules/@ergonode/products/src/components/Tabs/ProductGeneralTab.vue
- modules/@ergonode/products/src/components/Widgets/CompletenessWidget.vue
- modules/@ergonode/products/src/components/Widgets/ProductsWidget.vue
- modules/@ergonode/products/src/extends/components/Buttons/AddBindingAttributesButton.vue
- modules/@ergonode/products/src/extends/components/Buttons/AddProductsToGroupActionButton.vue
- modules/@ergonode/products/src/extends/components/Buttons/AddProductsToGroupButton.vue
- modules/@ergonode/products/src/extends/components/Grids/AttachedProductVariantsGrid.vue
- modules/@ergonode/products/src/extends/components/Grids/AttachedProductsToGroupGrid.vue
- modules/@ergonode/products/src/extends/components/Grids/ProductVariantsToAttachGrid.vue
- modules/@ergonode/products/src/extends/components/Grids/ProductsToAttachForGroupGrid.vue
- modules/@ergonode/products/src/extends/components/Modals/AddBindingAttributesModalForm.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductVariantsModalGrid.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsFromSegmentModalForm.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsToGroupModalGrid.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/products/src/pages/catalog/_product/_id.vue
- modules/@ergonode/products/src/pages/catalog/index.vue
> Product translations

- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/core/src/layouts/default.vue
- modules/@ergonode/products/src/components/BatchActions/ProductsBatchActions.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
> feature(core): improve delete products batch action

- modules/@ergonode/batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/batch-actions/src/components/ProductsBatchActions/ProductsBatchActions.vue
- modules/@ergonode/products/src/components/BatchActions/ProductsBatchActions.vue
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/ui/src/components/ActionButton/ActionBaseButton.vue
- modules/@ergonode/ui/src/components/Grid/Buttons/BatchActionButton.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridSelectRowColumn.vue
- modules/@ergonode/ui/src/components/Modal/ModalTabBar.vue
- modules/@ergonode/ui/src/components/SelectList/SelectListElement.vue
> Mass edit batch action modal

- modules/@ergonode/authentication/src/components/Forms/LoginForm.vue
- modules/@ergonode/ui/src/components/Form/Form.vue
- modules/@ergonode/ui/src/components/Form/Section/FormSection.vue
> Add support for custom form width

- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridDraggableColumn.vue
- modules/@ergonode/ui/src/models/dragAndDrop/getColumnsTransforms.js
- modules/@ergonode/ui/src/store/draggable/state.js
> Dragging columns inside modal above grid inside tab

- modules/@ergonode/batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormGhostItem.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormPlaceholderItem.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridDraggableColumn.vue
> Draggable form

- modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItemParameter.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArrayObject.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormTableRowWidget.vue
- channel privileges fix
- import privileges fix
- segment privileges fix
Issue #709 
> fix: privileges bug fix

- modules/@ergonode/channels/src/config/extends.js
- modules/@ergonode/import/src/config/extends.js
> Add progress notifications only for precessed status

- modules/@ergonode/ui/src/components/Icons/Arrows/IconArrowRoundedDropdown.vue
- modules/@ergonode/ui/src/components/TreeAccordion/TreeAccordionItemArrowExpander.vue
Replaced icon for tree accordion items from customised css / svg to pure svg
> Replace icon for accordion tree items

- modules/@ergonode/dashboard/src/pages/dashboard/index.vue
- modules/@ergonode/product-templates/src/extends/components/Forms/ProductFormTemplate.vue
- modules/@ergonode/product-templates/src/extends/store/product/state.js
- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
- Added pre loader to dashboard
- Fixed fetching current template 
> Dashboard preloader, product template

- modules/@ergonode/ui/src/mixins/grid/gridResizerCellMixin.js
- modules/@ergonode/users/src/components/Grids/RolePrivilegesGrid.vue
- modules/@ergonode/users/src/models/gridDataMapper.js
> Improve mass edit values at grid; add privileges dependency

- modules/@ergonode/attributes/src/components/Buttons/RemoveAttributeButton.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeFormOptions.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeFormParamsSelect.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeFormParamsToggle.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/category-trees/src/components/Tabs/CategoryTreeDesignerTab.vue
- modules/@ergonode/channels/src/extends/notification/components/Notifications/NotificationListExportProcessingItem.vue
- modules/@ergonode/collections/src/config/extendRoutesChildren.js
- modules/@ergonode/collections/src/config/routes.js
- modules/@ergonode/collections/src/extends/product/components/Tabs/ProductCollectionTab.vue
- modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
- modules/@ergonode/import/src/extends/notification/components/Notifications/NotificationListImportProcessingItem.vue
- modules/@ergonode/media/src/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
- modules/@ergonode/product-templates/src/components/Tabs/TemplateDesignerTab.vue
- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
- modules/@ergonode/products/src/extends/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
- modules/@ergonode/status-transitions/src/components/Tabs/ConditionDesignerTab.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
> Privileges improvement

- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeFormOptions.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeFormParamsSelect.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeFormParamsToggle.vue
> Attribute params

- modules/@ergonode/product-statuses/src/config/index.js
- modules/@ergonode/status-transitions/src/components/Buttons/UpdateProductStatusConditionDesignerButton.vue
- modules/@ergonode/status-transitions/src/components/Tabs/ConditionDesignerTab.vue
Change workflow relations. 
Issue #729 
> refactor: change workflow relations

- modules/@ergonode/categories/src/components/Buttons/CreateCategoryFab.vue
- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
- modules/@ergonode/collections/src/components/Forms/AddProductsBySKUForm.vue
- modules/@ergonode/collections/src/config/extendRoutesChildren.js
- modules/@ergonode/collections/src/config/routes.js
- modules/@ergonode/collections/src/extends/product/components/Tabs/ProductCollectionTab.vue
- modules/@ergonode/core/src/middleware/privilegeRoutingCheck.global.js
- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
- modules/@ergonode/products/src/extends/components/Forms/AddProductsBySKUForm.vue
- modules/@ergonode/ui/src/components/DatePicker/Calendar/DatePickerCalendar.vue
- modules/@ergonode/ui/src/components/DatePicker/DatePicker.vue
- modules/@ergonode/ui/src/components/DatePicker/DatePickerContent.vue
- modules/@ergonode/ui/src/components/DatePicker/DatePickerMonth.vue
- modules/@ergonode/ui/src/components/DatePicker/DatePickerMonths.vue
- modules/@ergonode/ui/src/components/Form/Form.vue
- modules/@ergonode/ui/src/models/calendar/index.js
- modules/@ergonode/users/src/components/Grids/RolePrivilegesGrid.vue
- modules/@ergonode/users/src/components/Tabs/RolePrivilegesTab.vue
- fix category tree privileges 
- datePicker - fix selected month
- datePicker - add possibility to disabled past date
- router privileges fix
- role privileges grid fix
Issue #740 
> bugfix: dataPicker fix, privileges fix, roles fix

- modules/@ergonode/notifications/src/components/NotificationList/Item/NotificationListItemTemplate.vue
- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
- modules/@ergonode/notifications/src/components/ToolBar/ToolBarNotificationButton.vue
- modules/@ergonode/notifications/src/locales/en_GB.json
- modules/@ergonode/notifications/src/locales/pl_PL.json
- modules/@ergonode/notifications/src/store/notification/actions.js
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeNotDefinedField.vue
- modules/@ergonode/products-batch-actions/src/components/Grids/ProductBatchActionDetailsGrid.vue
- modules/@ergonode/products-batch-actions/src/components/Modals/ProductBatchActionDetailsModalGrid.vue
- modules/@ergonode/products-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/products-batch-actions/src/components/NotificationLists/Items/NotificationListBatchActionEndedItem.vue
- modules/@ergonode/products-batch-actions/src/config/extends.js
- modules/@ergonode/products-batch-actions/src/config/imports.js
- modules/@ergonode/products-batch-actions/src/locales/en_GB.json
- modules/@ergonode/products-batch-actions/src/locales/pl_PL.json
- modules/@ergonode/products/src/store/product/actions.js
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormNotDefinedItem.vue
- modules/@ergonode/ui/src/components/ToolBar/ToolBarSelectButton.vue
Support for batch action notifications
> Notification support

- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/users/src/config/imports.js
> Grid crashes extended async component

- modules/@ergonode/products-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
- modules/@ergonode/products-batch-actions/src/components/Buttons/UpdateProductsButton.vue
- modules/@ergonode/products-batch-actions/src/services/index.js
Added initial filter when no ids are defined
> Add all filter support

- modules/@ergonode/activity-logs/src/config/imports.js
- modules/@ergonode/categories/src/config/imports.js
- modules/@ergonode/category-trees/src/config/imports.js
- modules/@ergonode/collections/src/config/imports.js
- modules/@ergonode/comments/src/config/imports.js
- modules/@ergonode/conditions/src/config/imports.js
- modules/@ergonode/core/src/config/imports.js
- modules/@ergonode/dashboard/src/config/imports.js
- modules/@ergonode/import/src/config/imports.js
- modules/@ergonode/media/src/config/imports.js
- modules/@ergonode/product-statuses/src/config/imports.js
- modules/@ergonode/product-templates/src/config/imports.js
- modules/@ergonode/products/src/config/imports.js
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/segments/src/config/imports.js
- modules/@ergonode/status-transitions/src/config/imports.js
- modules/@ergonode/users/src/config/imports.js
fix components imports.
Issue #744
> bugfix: fix components imports

- modules/@ergonode/batch-actions/src/components/BatchActionsListener/BatchActionsListener.vue
- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/batch-actions/src/store/batchAction/actions.js
- modules/@ergonode/batch-actions/src/store/batchAction/mutations.js
- modules/@ergonode/batch-actions/src/store/batchAction/state.js
- modules/@ergonode/products-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
> Async batch actions support

- modules/@ergonode/notifications/src/store/notification/actions.js
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeFormField.vue
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeMultiSelectFormField.vue
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeSelectFormField.vue
- modules/@ergonode/products-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormNotDefinedItem.vue
> Batch actions stabilisation - attributes

- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeDateFormField.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridDateDataCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridDateEditCell.vue
> fix(core): date unification

- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeFileFormField.vue
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeGalleryFormField.vue
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeImageFormField.vue
Support for media type attributes
> feature(batch-actions): add support for madia attributes

- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
- modules/@ergonode/products-batch-actions/src/components/Forms/Fields/AttributeSelectFormField.vue
- modules/@ergonode/ui/src/components/DatePicker/DatePickerContent.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
- show value on selected item on batch-action select
- fix scheduler form duplication
- fix JSONSchema validation error
> bugfix: fix scheduler, fix select type on batch-action

- modules/@ergonode/batch-actions/src/models/paramsSerializer.js
- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/products-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
- modules/@ergonode/products-batch-actions/src/components/Buttons/UpdateProductsButton.vue
- modules/@ergonode/products-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/products-batch-actions/src/locales/en_GB.json
- modules/@ergonode/products-batch-actions/src/locales/pl_PL.json
- modules/@ergonode/products-batch-actions/src/services/index.js
Support for the number of modified resources in a batch action
> feature(batch-actions): add row count before actions

- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/Filter/GridDateTimeFilterDataCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridDateTimeDataCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridDateTimeEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridDateTimeEditCell.vue
Add support for DATE_TIME type
> New column datetime

- modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateTimeType.vue
> Datetime advanced filter type

- modules/@ergonode/products-batch-actions/src/components/SideBars/AttributesSideBar.vue
show attributes as a common part in templates
> feature(batch-actions): filter attribute by templates

- modules/@ergonode/core/src/plugins/i18n.js
Fix default language on i18n translations
> bugfix(core): i18n fix default language

- CHANGELOG.md
- lerna.json
- modules/@ergonode/activity-logs/package.json
- modules/@ergonode/attributes/package.json
- modules/@ergonode/authentication/package.json
- modules/@ergonode/batch-actions/package.json
- modules/@ergonode/categories/package.json
- modules/@ergonode/category-trees/package.json
- modules/@ergonode/channels/package.json
- modules/@ergonode/collections/package.json
- modules/@ergonode/comments/package.json
- modules/@ergonode/conditions/package.json
- modules/@ergonode/core/package.json
- modules/@ergonode/dashboard/package.json
- modules/@ergonode/import/package.json
- modules/@ergonode/media/package.json
- modules/@ergonode/notifications/package.json
- modules/@ergonode/product-statuses/package.json
- modules/@ergonode/product-templates/package.json
- modules/@ergonode/products-batch-actions/package.json
- modules/@ergonode/products/package.json
- modules/@ergonode/segments/package.json
- modules/@ergonode/status-transitions/package.json
- modules/@ergonode/ui/package.json
- modules/@ergonode/users/package.json
- package.json
> Release/1.0.0 rc.1

- modules/@ergonode/products-batch-actions/src/components/Modals/ProductBatchActionDetailsModalGrid.vue
> hotfix: import error

- modules/@ergonode/ui/src/components/ActionButton/ActionBaseButton.vue
- modules/@ergonode/ui/src/components/List/ListElement.vue
- modules/@ergonode/ui/src/components/RichTextEditor/Button/RichTextEditorButton.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
Add better handling mouse events for RTE 
> RTE better handling mouse events

- modules/@ergonode/batch-actions/src/models/batchActionMapper.js
- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/product-batch-actions/src/components/Buttons/ProductsBatchActionsButton.vue
- modules/@ergonode/product-batch-actions/src/components/SideBars/AttributesSideBar.vue
- modules/@ergonode/product-batch-actions/src/services/index.js
Change batch-actions endpoint type. 
Issue #766 
> refactor(batch-actions): change endpoint type

- modules/@ergonode/batch-actions/src/models/batchActionMapper.js
- modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/product-batch-actions/src/components/SideBars/AttributesSideBar.vue
- modules/@ergonode/product-batch-actions/src/components/VerticalTabs/AttributesVerticalTab.vue
> Add missing filter

- modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesigner.vue
- modules/@ergonode/conditions/src/store/condition/actions.js
- modules/@ergonode/core/src/models/arrayWrapper.js
- modules/@ergonode/core/src/models/mappers/errorsMapper.js
- modules/@ergonode/core/src/models/mappers/gridDataMapper.js
- modules/@ergonode/core/src/store/dictionaries/state.js
- modules/@ergonode/core/src/store/feedback/actions.js
- modules/@ergonode/core/src/store/feedback/mutations.js
- modules/@ergonode/product-templates/src/components/TemplateDesigner/ProductDesigner/LayoutElement.vue
- modules/@ergonode/product-templates/src/models/layout/TemplateDesignerCalculations.js
- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
- modules/@ergonode/products/src/store/product/actions.js
- modules/@ergonode/ui/src/components/CheckBox/CheckBox.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/GridTableCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridActionColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridColumn.vue
- grid filter builder
- template resizing
- errors validations
- clean code
> Stabilisation

- modules/@ergonode/ui/src/mixins/inputs/associatedLabelMixin.js
- nuxt.config.js
> Memory leak, webpack config improvement

- modules/@ergonode/core/src/plugins/i18n.js
- nuxt.config.js
> Interface translation flashing on page reload

- modules/@ergonode/products/src/extends/components/BindingAttributes/AddBindingAttributes.vue
- modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttribute.vue
- modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttributes.vue
- modules/@ergonode/products/src/extends/components/Grids/AttachedProductVariantsGrid.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
…riants are chosen
Prevent from adding / removing binding attributes when any product variant is chosen
> Prevent from adding / removing binding attributes

- modules/@ergonode/notifications/src/components/NotificationList/Item/NotificationListItemTemplate.vue
- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
- modules/@ergonode/notifications/src/components/NotificationList/NotificationListMenu.vue
Change notification fetch data. 
Fix unread notifications.
Issue #780 
> bugfix(notification): fetch data

- modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
- modules/@ergonode/core/src/store/core/getters.js
- modules/@ergonode/product-statuses/src/components/Widgets/StatusesWidget.vue
Instead of filtering languages in each select, created getter.
Return first available language by privileges when user language privilege is not granted
> Improve languages validation

- modules/@ergonode/batch-actions/src/models/batchActionMapper.js
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/GridFooter.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridSelectEditContentCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridTextEditContentCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/GridSelectRowActionFabCell.vue
> Grid z-indexes, batch action filter

- modules/@ergonode/ui/src/components/Input/InputLabel.vue
- modules/@ergonode/ui/src/components/Input/InputSelectValue.vue
- modules/@ergonode/ui/src/components/Input/InputSolidStyle.vue
- modules/@ergonode/ui/src/components/Input/InputUnderlineStyle.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
- modules/@ergonode/ui/src/components/TextArea/TextArea.vue
- modules/@ergonode/ui/src/components/TextField/TextField.vue
Increased the color of disabled inputs by one level
> Increase color for disabled inputs

- modules/@ergonode/core/src/models/mappers/errorsMapper.js
> Displaying conditions error messages

- .eslintignore
- .github/ISSUE_TEMPLATE/question.md
- .gitignore
- README.md
> dosc: new slack link

- modules/@ergonode/ui/src/components/TreeDesigner/TreeDesigner.vue
Include hidden children on save
> Include hidden tree child on save category tree

- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeMultiSelectFormField.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
> Add missing clear / ok action

- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeSelectFormField.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormSelect.vue
- add missing props to edit batch action select
- add missing props to JSONSchema
> Add missing clearable props to Select

- modules/@ergonode/authentication/src/components/Forms/PasswordRecoveryCheckEmail.vue
- modules/@ergonode/core/src/pages/placeholder/index.vue
- modules/@ergonode/dashboard/src/components/Widgets/StatusesWidget.vue
- modules/@ergonode/products/src/extends/components/BindingAttributes/AddBindingAttributes.vue
- modules/@ergonode/products/src/extends/components/BindingAttributes/BindingAttribute.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/AdvancedFiltersRemoveAllButton.vue
- modules/@ergonode/ui/src/components/Fab/Fab.vue
- modules/@ergonode/ui/src/components/IconButton/IconButton.vue
- modules/@ergonode/ui/src/components/LinkButton/LinkButton.vue
- modules/@ergonode/ui/src/components/MenuList/MenuListElement.vue
- modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBar.vue
- modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarElement.vue
- modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarGroupElement.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
- modules/@ergonode/ui/src/components/TabBar/HorizontalTabBarItem.vue
- modules/@ergonode/ui/src/components/TabBar/VerticalTabBarItem.vue
- modules/@ergonode/ui/src/components/TitleBar/TitleBarBreadcrumb.vue
- modules/@ergonode/ui/src/components/TitleBar/__tests__/__snapshots__/TitleBarBreadcrumb.test.js.snap
- modules/@ergonode/ui/src/components/ToolBar/ToolBarBreadcrumb.vue
- modules/@ergonode/ui/src/components/ToolBar/ToolBarButton.vue
> bugfix: fixes to html validator

- modules/@ergonode/ui/src/components/Button/Button.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaForm.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormSelect.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormText.vue
- Add description support for JSON Schema fields
- Fixed button width
> feat(core): JSON Schema description support

- modules/@ergonode/core/src/models/mappers/__tests__/__mocks__/treeDesigner.mock.js
- modules/@ergonode/core/src/models/mappers/__tests__/treeDesignerMapper.test.js
- modules/@ergonode/core/src/models/mappers/treeDesignerMapper.js
- modules/@ergonode/ui/src/components/TreeDesigner/TreeDesigner.vue
Prevent from missing hidden items on tree designer update
> Category tree hidden missing items

- modules/@ergonode/attributes/src/components/Modals/CreateAttributeModalForm.vue
- modules/@ergonode/attributes/src/locales/en_GB.json
- modules/@ergonode/attributes/src/locales/pl_PL.json
Add missing scope to the create attribute action
> Add missing scope

- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
Prevent route query replace when no needed
> Routing duplication calls

- modules/@ergonode/products/src/components/Buttons/ProductWorkflowActionButton.vue
- modules/@ergonode/products/src/components/Progress/ProductCompleteness.vue
Remove infinity loop on get workflow and completeness
> Product infinity loop

- modules/@ergonode/authentication/src/store/authentication/actions.js
- modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
- modules/@ergonode/core/src/components/Tabs/TranslationsTab.vue
- modules/@ergonode/core/src/store/core/getters.js
- modules/@ergonode/dashboard/src/components/Widgets/StatusesWidget.vue
- modules/@ergonode/users/src/store/user/actions.js
> Improve language validation

- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
> Remove column data

- modules/@ergonode/ui/src/components/TreeDesigner/TreeDesigner.vue
> Prevent from removing too many children on drag at trash

- modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
- modules/@ergonode/core/src/components/Tabs/TranslationsTab.vue
- modules/@ergonode/product-batch-actions/src/components/SideBars/AttributesSideBar.vue
- translations crash
- global attributes are not going to be displayed any more in attributes sidebar for edit batch action
- alert message
> Local attributes, translations

- modules/@ergonode/ui/src/components/Card/Card.vue
> Fix css order property

- modules/@ergonode/products/src/config/extends.js
> bugfix: product extended tabs

- modules/@ergonode/batch-actions/src/config/extends.js
- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
> Translation crash

- modules/@ergonode/core/src/components/Tabs/TranslationsTab.vue
> Initial translation language

- modules/@ergonode/segments/src/components/Forms/SegmentTranslationForm.vue
> Add missing translation

- modules/@ergonode/batch-actions/src/config/extends.js
Batch action extend translation fix.
> bugfix(batch-action): translation fix

- CHANGELOG.md
- lerna.json
- modules/@ergonode/activity-logs/package.json
- modules/@ergonode/attribute-groups/package.json
- modules/@ergonode/attributes/package.json
- modules/@ergonode/authentication/package.json
- modules/@ergonode/batch-actions/package.json
- modules/@ergonode/categories/package.json
- modules/@ergonode/category-trees/package.json
- modules/@ergonode/channels/package.json
- modules/@ergonode/collections/package.json
- modules/@ergonode/comments/package.json
- modules/@ergonode/conditions/package.json
- modules/@ergonode/core/package.json
- modules/@ergonode/dashboard/package.json
- modules/@ergonode/import/package.json
- modules/@ergonode/media/package.json
- modules/@ergonode/notifications/package.json
- modules/@ergonode/product-batch-actions/package.json
- modules/@ergonode/product-statuses/package.json
- modules/@ergonode/product-templates/package.json
- modules/@ergonode/products-comments/package.json
- modules/@ergonode/products/package.json
- modules/@ergonode/roles/package.json
- modules/@ergonode/segments/package.json
- modules/@ergonode/status-transitions/package.json
- modules/@ergonode/ui/package.json
- modules/@ergonode/users/package.json
- package.json
> Release/1.0.0 rc.2

- modules/@ergonode/activity-logs/src/pages/activity-logs/index.vue
- modules/@ergonode/attribute-groups/src/pages/attribute-groups/index.vue
- modules/@ergonode/attributes/src/pages/attributes/index.vue
- modules/@ergonode/categories/src/pages/categories/index.vue
- modules/@ergonode/category-trees/src/pages/category-trees/index.vue
- modules/@ergonode/channels/src/pages/channels/index.vue
- modules/@ergonode/collections/src/pages/collections/index.vue
- modules/@ergonode/core/src/pages/settings/index.vue
- modules/@ergonode/import/src/pages/imports/index.vue
- modules/@ergonode/media/src/pages/media/index.vue
- modules/@ergonode/product-statuses/src/pages/product-statuses/index.vue
- modules/@ergonode/product-templates/src/pages/product-templates/index.vue
- modules/@ergonode/products/src/pages/catalog/index.vue
- modules/@ergonode/roles/src/pages/roles/index.vue
- modules/@ergonode/segments/src/pages/segments/index.vue
- modules/@ergonode/status-transitions/src/pages/status-transitions/index.vue
- modules/@ergonode/users/src/pages/profile/index.vue
- modules/@ergonode/users/src/pages/users/index.vue
> Remove legacy modal injection

- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Grid placeholder was getting pushed to the bottom when no data
> Placeholder position

- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormMultiSelectField.vue
Product multiselect attribute was missing parsing
> Add parsing for multiselect attribute

- modules/@ergonode/ui/src/components/TextField/TextField.vue
> Input box shadow 

- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
> Add missing draggable form width support

- modules/@ergonode/notifications/src/components/NotificationList/Item/NotificationListItemTemplate.vue
- modules/@ergonode/product-batch-actions/src/components/NotificationLists/Items/NotificationListBatchActionEndedItem.vue
Remove details preview from notification items
> Prevent notification details preview 

- modules/@ergonode/status-transitions/src/components/Buttons/CreateStatusTransitionButton.vue
- modules/@ergonode/status-transitions/src/components/Buttons/RemoveStatusTransitionButton.vue
- modules/@ergonode/status-transitions/src/components/Buttons/UpdateProductStatusConditionDesignerButton.vue
- modules/@ergonode/status-transitions/src/components/DropZones/RemoveConditionDropZone.vue
- modules/@ergonode/status-transitions/src/components/Forms/TransitionForm.vue
- modules/@ergonode/status-transitions/src/components/Grids/TransitionsGrid.vue
- modules/@ergonode/status-transitions/src/components/Modals/CreateStatusTransitionModalForm.vue
- modules/@ergonode/status-transitions/src/components/Tabs/ConditionDesignerTab.vue
- modules/@ergonode/status-transitions/src/components/Tabs/TransitionGeneralTab.vue
- modules/@ergonode/status-transitions/src/locales/en_GB.json
- modules/@ergonode/status-transitions/src/locales/pl_PL.json
- modules/@ergonode/status-transitions/src/pages/status-transitions/_transition/_id.vue
- modules/@ergonode/status-transitions/src/pages/status-transitions/index.vue
- modules/@ergonode/status-transitions/src/store/statusTransition/actions.js
> Status transition translations

- modules/@ergonode/products/src/components/Buttons/RemoveProductButton.vue
- modules/@ergonode/products/src/components/Buttons/UpdateProductTemplateButton.vue
- modules/@ergonode/products/src/components/Chart/DoughnutProductsChart.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormNoTypeField.vue
- modules/@ergonode/products/src/components/Forms/ProductForm.vue
- modules/@ergonode/products/src/components/Forms/ProductTemplateForm.vue
- modules/@ergonode/products/src/components/Grids/ProductHistoryGrid.vue
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/products/src/components/Modals/CreateProductModalForm.vue
- modules/@ergonode/products/src/components/Modals/RestoreAttributeParentConfirmModal.vue
- modules/@ergonode/products/src/components/Progress/ProductCompleteness.vue
- modules/@ergonode/products/src/components/Progress/__tests__/ProductCompleteness.test.js
- modules/@ergonode/products/src/components/Tabs/ProductGeneralTab.vue
- modules/@ergonode/products/src/extends/components/Buttons/AddProductVariantsButton.vue
- modules/@ergonode/products/src/extends/components/Buttons/UpdateProductsAttachmentButton.vue
- modules/@ergonode/products/src/extends/components/Forms/AddProductsBySKUForm.vue
- modules/@ergonode/products/src/extends/components/Forms/Field/ProductAttributeBindingField.vue
- modules/@ergonode/products/src/extends/components/Forms/ProductAttributesBindingForm.vue
- modules/@ergonode/products/src/extends/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
- modules/@ergonode/products/src/extends/components/Grids/AttachedProductsToGroupGrid.vue
- modules/@ergonode/products/src/extends/components/Modals/AddBindingAttributesModalForm.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsBySKUModalForm.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsFromSegmentModalForm.vue
- modules/@ergonode/products/src/extends/components/Tabs/ProductVariantsTab.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
Add missing product interface translations
> Product interface translations

- modules/@ergonode/segments/src/components/Autocompletes/SegmentsAutocomplete.vue
- modules/@ergonode/segments/src/components/Buttons/CreateSegmentButton.vue
- modules/@ergonode/segments/src/components/Buttons/RemoveSegmentButton.vue
- modules/@ergonode/segments/src/components/Buttons/UpdateSegmentConditionDesignerButton.vue
- modules/@ergonode/segments/src/components/Buttons/UpdateSegmentTranslationButton.vue
- modules/@ergonode/segments/src/components/DropZones/RemoveConditionDropZone.vue
- modules/@ergonode/segments/src/components/Forms/SegmentForm.vue
- modules/@ergonode/segments/src/components/Forms/SegmentTranslationForm.vue
- modules/@ergonode/segments/src/components/Grids/SegmentsGrid.vue
- modules/@ergonode/segments/src/components/Modals/CreateSegmentModalForm.vue
- modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
- modules/@ergonode/segments/src/components/Tabs/SegmentGeneralTab.vue
- modules/@ergonode/segments/src/locales/en_GB.json
- modules/@ergonode/segments/src/locales/pl_PL.json
- modules/@ergonode/segments/src/pages/segments/_segment/_id.vue
- modules/@ergonode/segments/src/pages/segments/index.vue
- modules/@ergonode/segments/src/store/segment/actions.js
- modules/@ergonode/ui/src/components/DropZone/DropZone.vue
> Segment translations

- modules/@ergonode/product-statuses/src/components/Buttons/CreateProductStatusButton.vue
- modules/@ergonode/product-statuses/src/components/Buttons/RemoveProductStatusButton.vue
- modules/@ergonode/product-statuses/src/components/Buttons/UpdateProductStatusTranslationButton.vue
- modules/@ergonode/product-statuses/src/components/Forms/ProductStatusForm.vue
- modules/@ergonode/product-statuses/src/components/Forms/ProductStatusTranslationForm.vue
- modules/@ergonode/product-statuses/src/components/Grids/ProductStatusesGrid.vue
- modules/@ergonode/product-statuses/src/components/Modals/CreateProductStatusModalForm.vue
- modules/@ergonode/product-statuses/src/components/Tabs/ProductStatusGeneralTab.vue
- modules/@ergonode/product-statuses/src/locales/en_GB.json
- modules/@ergonode/product-statuses/src/locales/pl_PL.json
- modules/@ergonode/product-statuses/src/pages/product-statuses/_status/_id.vue
- modules/@ergonode/product-statuses/src/pages/product-statuses/index.vue
- modules/@ergonode/product-statuses/src/store/productStatus/actions.js
> Product statuses interface translations

- modules/@ergonode/product-templates/src/components/Autocompletes/ProductTemplatesAutocomplete.vue
- modules/@ergonode/product-templates/src/components/Buttons/CreateProductTemplateButton.vue
- modules/@ergonode/product-templates/src/components/Buttons/RemoveProductTemplateButton.vue
- modules/@ergonode/product-templates/src/components/Buttons/UpdateTemplateDesignerButton.vue
- modules/@ergonode/product-templates/src/components/DropZones/RemoveElementDropZone.vue
- modules/@ergonode/product-templates/src/components/Forms/ProductTemplateForm.vue
- modules/@ergonode/product-templates/src/components/Grids/ProductTemplatesGrid.vue
- modules/@ergonode/product-templates/src/components/Modals/CreateProductTemplateModalForm.vue
- modules/@ergonode/product-templates/src/components/Modals/SectionTemplateModalForm.vue
- modules/@ergonode/product-templates/src/components/SideBars/WidgetsSideBar.vue
- modules/@ergonode/product-templates/src/components/Tabs/ProductTemplateGeneralTab.vue
- modules/@ergonode/product-templates/src/components/Tabs/TemplateDesignerTab.vue
- modules/@ergonode/product-templates/src/locales/en_GB.json
- modules/@ergonode/product-templates/src/locales/pl_PL.json
- modules/@ergonode/product-templates/src/pages/product-templates/_template/_id.vue
- modules/@ergonode/product-templates/src/pages/product-templates/index.vue
- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
> Product template interface translations

- modules/@ergonode/media/src/components/Buttons/LinkRelationButton.vue
- modules/@ergonode/media/src/components/Buttons/RemoveResourceButton.vue
- modules/@ergonode/media/src/components/Buttons/UpdateResourceTranslationButton.vue
- modules/@ergonode/media/src/components/Buttons/UploadResourcesButton.vue
- modules/@ergonode/media/src/components/Forms/ResourceForm.vue
- modules/@ergonode/media/src/components/Forms/ResourceRelationsForm.vue
- modules/@ergonode/media/src/components/Forms/ResourceTranslationForm.vue
- modules/@ergonode/media/src/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
- modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
- modules/@ergonode/media/src/components/Grids/MediaGrid.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/media/src/components/Modal/ModalMediaTabBar.vue
- modules/@ergonode/media/src/components/Tabs/ResourceGeneralTab.vue
- modules/@ergonode/media/src/components/Tabs/UploadFileTab.vue
- modules/@ergonode/media/src/locales/en_GB.json
- modules/@ergonode/media/src/locales/pl_PL.json
- modules/@ergonode/media/src/pages/media/_resource/_id.vue
- modules/@ergonode/media/src/pages/media/index.vue
- modules/@ergonode/product-statuses/src/pages/product-statuses/_status/_id.vue
- modules/@ergonode/segments/src/pages/segments/_segment/_id.vue
- modules/@ergonode/status-transitions/src/locales/pl_PL.json
> Media interface translation

- modules/@ergonode/import/src/components/Buttons/CreateImportButton.vue
- modules/@ergonode/import/src/components/Buttons/CreateImportProfileButton.vue
- modules/@ergonode/import/src/components/Buttons/RemoveImportButton.vue
- modules/@ergonode/import/src/components/Buttons/UploadImportButton.vue
- modules/@ergonode/import/src/components/Forms/ImportProfileForm.vue
- modules/@ergonode/import/src/components/Grids/ImportProfileHistoryGrid.vue
- modules/@ergonode/import/src/components/Grids/ImportProfilesGrid.vue
- modules/@ergonode/import/src/components/Modals/CreateImportProfileModalForm.vue
- modules/@ergonode/import/src/components/Modals/ImportDetailsModalGrid.vue
- modules/@ergonode/import/src/components/Modals/UploadImportFileModalForm.vue
- modules/@ergonode/import/src/components/Tabs/ImportProfileGeneralTab.vue
- modules/@ergonode/import/src/locales/en_GB.json
- modules/@ergonode/import/src/locales/pl_PL.json
- modules/@ergonode/import/src/pages/imports/_import/_id.vue
- modules/@ergonode/import/src/pages/imports/index.vue
- modules/@ergonode/import/src/store/import/actions.js
> Import interface translations

- modules/@ergonode/channels/src/components/Buttons/CreateChannelButton.vue
- modules/@ergonode/channels/src/components/Buttons/CreateExportButton.vue
- modules/@ergonode/channels/src/components/Buttons/DownloadExportFileButton.vue
- modules/@ergonode/channels/src/components/Buttons/RemoveChannelButton.vue
- modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
- modules/@ergonode/channels/src/components/Grids/ChannelHistoryGrid.vue
- modules/@ergonode/channels/src/components/Grids/ChannelsGrid.vue
- modules/@ergonode/channels/src/components/Grids/ExportDetailsGrid.vue
- modules/@ergonode/channels/src/components/Modals/CreateChannelModalForm.vue
- modules/@ergonode/channels/src/components/Modals/ExportDetailsModalGrid.vue
- modules/@ergonode/channels/src/components/Tabs/ChannelGeneralTab.vue
- modules/@ergonode/channels/src/components/Tabs/ChannelSchedulerTab.vue
- modules/@ergonode/channels/src/locales/en_GB.json
- modules/@ergonode/channels/src/locales/pl_PL.json
- modules/@ergonode/channels/src/pages/channels/_channel/_id.vue
- modules/@ergonode/channels/src/pages/channels/index.vue
- modules/@ergonode/channels/src/store/channel/actions.js
- modules/@ergonode/import/src/store/import/actions.js
- modules/@ergonode/segments/src/store/segment/actions.js
> Channel interface translation

- modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
- modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
- modules/@ergonode/core/src/components/Tabs/UnitGeneralTab.vue
- modules/@ergonode/core/src/locales/en_GB.json
- modules/@ergonode/core/src/locales/pl_PL.json
- modules/@ergonode/core/src/plugins/axios.js
- modules/@ergonode/ui/src/components/ColorPicker/ColorPicker.vue
- modules/@ergonode/ui/src/components/Grid/Modals/GridSettingsModalForm.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Footers/SelectDropdownApplyFooter.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Footers/SelectDropdownFooter.vue
> Core interface translation

- modules/@ergonode/conditions/src/components/SideBars/ConditionsSideBar.vue
- modules/@ergonode/conditions/src/locales/en_GB.json
- modules/@ergonode/conditions/src/locales/pl_PL.json
> Condition interface translation

- modules/@ergonode/collections/src/extends/product/components/Collection/ProductCollectionItem.vue
- modules/@ergonode/core/src/services/grid/getGridData.service.js
- modules/@ergonode/media/src/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/media/src/extends/product/components/Forms/Field/ProductTemplateFormGalleryField.vue
- modules/@ergonode/media/src/extends/product/components/Forms/Field/ProductTemplateFormImageField.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/products/src/components/Inputs/UploadProductRelations.vue
- modules/@ergonode/products/src/components/Modals/AddProductRelationsModalGrid.vue
- modules/@ergonode/products/src/components/ProductCarousel/ProductCarousel.vue
- modules/@ergonode/products/src/extends/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/ui/src/components/DefaultImage/DefaultImage.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionDefaultCell.vue
- modules/@ergonode/ui/src/components/Input/InputController.vue
…t image component
- implemented uploader for product relation
- implemented default image component
- improve image placeholders and sizes
Issue #846 
> Product relation uploader

- modules/@ergonode/products/src/components/Icons/IconRelation.vue
- modules/@ergonode/products/src/config/extends.js
- modules/@ergonode/products/src/config/imports.js
- modules/@ergonode/products/src/defaults/index.js
Add icon for the new attribute type. 
Issue #846 
> feature: new attribute icon

- modules/@ergonode/attribute-groups/src/locales/pl_PL.json
- modules/@ergonode/attributes/src/locales/pl_PL.json
- modules/@ergonode/categories/src/locales/pl_PL.json
- modules/@ergonode/category-trees/src/locales/pl_PL.json
- modules/@ergonode/channels/src/components/Grids/ChannelHistoryGrid.vue
- modules/@ergonode/channels/src/locales/pl_PL.json
- modules/@ergonode/collections/src/locales/pl_PL.json
- modules/@ergonode/comments/src/locales/pl_PL.json
- modules/@ergonode/conditions/src/config/extends.js
- modules/@ergonode/conditions/src/locales/en_GB.json
- modules/@ergonode/conditions/src/locales/pl_PL.json
- modules/@ergonode/media/src/locales/pl_PL.json
- modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
- modules/@ergonode/product-templates/src/config/extends.js
- modules/@ergonode/product-templates/src/locales/en_GB.json
- modules/@ergonode/product-templates/src/locales/pl_PL.json
- modules/@ergonode/products/src/components/Modals/RestoreProductAttributesModalForm.vue
- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/roles/src/locales/pl_PL.json
- modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
- modules/@ergonode/segments/src/locales/en_GB.json
- modules/@ergonode/segments/src/locales/pl_PL.json
- modules/@ergonode/status-transitions/src/locales/pl_PL.json
- modules/@ergonode/users/src/locales/pl_PL.json
Improving interface translations for Polish language
> Polish interface translations improvement

- modules/@ergonode/roles/src/store/role/actions.js
Add a default property value for method updateRole.
Issue #855 
> bugfix: role update action fix

- modules/@ergonode/roles/src/store/role/actions.js
Add a default property value for method `updateRole`.
Issue #855 
> bugfix: role default update property

- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeProductRelationFormField.vue
> Add batch action product relation form component

- cypress/integration/9:roles/1:create.feature
- cypress/integration/9:roles/1:create/index.test.js
- cypress/integration/9:roles/2:read.feature
- cypress/integration/9:roles/2:read/index.test.js
- cypress/integration/9:roles/3:update.feature
- cypress/integration/9:roles/3:update/index.test.js
- cypress/integration/9:roles/4:delete.feature
- cypress/integration/9:roles/4:delete/index.test.js
- cypress/integration/common/inputs.test.js
- cypress/models/navigation.js
- modules/@ergonode/roles/src/components/Buttons/CreateRoleButton.vue
- modules/@ergonode/roles/src/components/Buttons/RemoveRoleButton.vue
- modules/@ergonode/roles/src/components/Forms/UserRoleForm.vue
- modules/@ergonode/roles/src/store/role/actions.js
> test: e2e for roles

- modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
> Add sorting to the media grid

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/categories/src/config/extends.js
- modules/@ergonode/category-trees/src/config/extends.js
- modules/@ergonode/product-batch-actions/src/config/extends.js
> Interface translations template crash

- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridGalleryEditCell.vue
- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeProductRelationFormField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormProductRelationField.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
- modules/@ergonode/products/src/components/Inputs/UploadProductRelations.vue
- modules/@ergonode/products/src/components/Modals/AddProductRelationsModalGrid.vue
- modules/@ergonode/products/src/components/ProductCarousel/ProductCarousel.vue
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridProductRelationEditCell.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
When editing single product, the modal with product relations is going to have filter and sort functionality. 
When editing multiple products - product batch action, filter and sort functionality is not available
Issue #846
> Integrate product relation endpoint

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/categories/src/config/extends.js
- modules/@ergonode/category-trees/src/config/extends.js
- modules/@ergonode/conditions/src/config/extends.js
- modules/@ergonode/product-batch-actions/src/config/extends.js
- modules/@ergonode/product-templates/src/config/extends.js
> Incorrect method call - i18n

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/categories/src/config/extends.js
- modules/@ergonode/category-trees/src/config/extends.js
- modules/@ergonode/conditions/src/config/extends.js
- modules/@ergonode/product-batch-actions/src/config/extends.js
- modules/@ergonode/product-templates/src/config/extends.js
> App translation crash

- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
Presenting columns in SKU, Attached, Template, Default label, Default image order
Issue #846 
> Present columns in correct order

- modules/@ergonode/product-statuses/src/store/productStatus/actions.js
> Correct default status value mapping

- modules/@ergonode/categories/src/locales/pl_PL.json
- modules/@ergonode/category-trees/src/locales/pl_PL.json
- modules/@ergonode/collections/src/components/Buttons/UpdateCollectionProductsVisibilityButton.vue
- modules/@ergonode/collections/src/locales/en_GB.json
- modules/@ergonode/collections/src/locales/pl_PL.json
- modules/@ergonode/core/src/components/Buttons/CreateUnitButton.vue
- modules/@ergonode/core/src/components/Buttons/UpdateLanguagesInheritanceButton.vue
- modules/@ergonode/core/src/components/DropZones/RemoveElementDropZone.vue
- modules/@ergonode/core/src/components/Forms/UnitForm.vue
- modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
- modules/@ergonode/core/src/components/SideBars/LanguagesSideBar.vue
- modules/@ergonode/core/src/components/Tabs/LanguagesSettingsTab.vue
- modules/@ergonode/core/src/config/extends.js
- modules/@ergonode/core/src/locales/en_GB.json
- modules/@ergonode/core/src/locales/pl_PL.json
- modules/@ergonode/core/src/store/core/actions.js
- modules/@ergonode/product-templates/src/locales/en_GB.json
- modules/@ergonode/product-templates/src/locales/pl_PL.json
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/segments/src/components/Tabs/ConditionDesignerTab.vue
- modules/@ergonode/users/src/locales/pl_PL.json
> Missing polish translations

- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
> Improve column order

- modules/@ergonode/categories/src/locales/pl_PL.json
- modules/@ergonode/core/src/locales/en_GB.json
- modules/@ergonode/core/src/locales/pl_PL.json
- modules/@ergonode/core/src/pages/settings/index.vue
- modules/@ergonode/products/src/locales/pl_PL.json
> Polish translations improvement

- modules/@ergonode/categories/src/locales/pl_PL.json
- modules/@ergonode/core/src/locales/en_GB.json
- modules/@ergonode/core/src/locales/pl_PL.json
- modules/@ergonode/core/src/pages/settings/index.vue
- modules/@ergonode/products/src/locales/pl_PL.json
> Polish translations

- modules/@ergonode/ui/src/components/ColorPicker/ColorPicker.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
- modules/@ergonode/ui/src/components/TextArea/TextArea.vue
- modules/@ergonode/workflow/src/components/Badges/WorkflowStatusBadge.vue
- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowStatusButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowStatusButton.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateTransitionsButton.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowStatusTranslationButton.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerEditStatusLink.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusTranslationForm.vue
- modules/@ergonode/workflow/src/components/Inputs/ColorPickerInputValue.vue
- modules/@ergonode/workflow/src/components/Inputs/WorkflowStatusPreview.vue
- modules/@ergonode/workflow/src/components/Modals/CreateWorkflowStatusModalForm.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowStatusGeneralTab.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowStatusTranslationsTab.vue
- modules/@ergonode/workflow/src/config/imports.js
- modules/@ergonode/workflow/src/config/routes.js
- modules/@ergonode/workflow/src/defaults/index.js
- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
- modules/@ergonode/workflow/src/pages/workflow/_status/_id.vue
- modules/@ergonode/workflow/src/pages/workflow/index.vue
- modules/@ergonode/workflow/src/services/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
- modules/@ergonode/workflow/src/store/workflow/state.js
Add support for create / edit workflow status
Issue #882 
> Support for create / edit workflow status

- jest.config.js
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerBackgroundItem.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerDefaultStatusPlaceholder.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
- modules/@ergonode/workflow/src/components/Inputs/ColorPickerInputValue.vue
- modules/@ergonode/workflow/src/components/Inputs/WorkflowStatusPreview.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowDesignerTab.vue
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/WorkflowDesignerCalculations.test.js
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
Created algorithm which will give user feedback at which cell can add transition "to"
Issue #882 
> Highlighting workflow designer background item

- modules/@ergonode/conditions/src/config/extends.js
- modules/@ergonode/conditions/src/services/index.js
- modules/@ergonode/roles/src/config/extends.js
- modules/@ergonode/workflow/src/components/Buttons/CreateWorflowTransitionButton.vue
- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTransitionConditionDesignerButton.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTranslationButton.vue
- modules/@ergonode/workflow/src/components/DropZones/RemoveTransitionConditionDropZone.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowTransitionForm.vue
- modules/@ergonode/workflow/src/components/Modals/CreateWorkflowTransitionModalForm.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowDesignerTab.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowStatusTranslationsTab.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowTransitionConditionDesignerTab.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowTransitionGeneralTab.vue
- modules/@ergonode/workflow/src/config/imports.js
- modules/@ergonode/workflow/src/config/routes.js
- modules/@ergonode/workflow/src/defaults/index.js
- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
- modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
- modules/@ergonode/workflow/src/services/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
- modules/@ergonode/workflow/src/store/workflow/state.js
Add support for create / edit transition through the process without involving workflow designer
Issue #882 
> Support for transition create / edit

- modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
- modules/@ergonode/import/src/components/Forms/ImportProfileForm.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaForm.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArray.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormArrayString.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormObject.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormSelect.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormString.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormTableRowWidget.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormText.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaOneOf.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/Widget/JSONSchemaFormDictionaryWidget.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/Widget/JSONSchemaFormDictionaryWidgetRow.vue
- package-lock.json
> Improve JSON schema widget rendering mechanism

- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaFormObject.vue
- modules/@ergonode/ui/src/components/Form/JSONSchemaForm/JSONSchemaOneOf.vue
The data in the fields are not preserved, fix JSON schema form. 
Issue #891 
> bugfix(channel): JSON schema oneOf form

- cypress/integration/11:workflow/status/1:create.feature
- cypress/integration/11:workflow/status/1:create/index.test.js
- cypress/integration/11:workflow/status/2:read.feature
- cypress/integration/11:workflow/status/2:read/index.test.js
- cypress/integration/11:workflow/status/3:update.feature
- cypress/integration/11:workflow/status/3:update/index.test.js
- cypress/integration/11:workflow/status/4:delete.feature
- cypress/integration/11:workflow/status/4:delete/index.test.js
- cypress/integration/common/actions.test.js
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowDesignerTab.vue
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/WorkflowDesignerCalculations.test.js
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
- package-lock.json
- e2e test for workflow statuses
- unit tests
Issue #882 
> Er 1197/status e2e

- modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
Bugfix for workflow transition 
Issue #882 
> bugfix: workflow transition bugs

- modules/@ergonode/attributes/src/services/index.js
- modules/@ergonode/attributes/src/store/attribute/actions.js
- modules/@ergonode/products/src/store/product/actions.js
Attribute validation with new param. Param for check product id.
> feature: attribute validation with param

- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
Remove wrong mouse position for transition arrow when removing start pointer.
Issue #882 
> remove wrong cursor position when remove

- modules/@ergonode/attributes/src/services/index.js
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
- modules/@ergonode/products/src/store/product/actions.js
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/GridDataCell.vue
Fix attribute validation message on product grid.
> bugfix: validation message

- modules/@ergonode/products/src/components/Buttons/AddProductRelationsButton.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormProductRelationField.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
- modules/@ergonode/products/src/components/Inputs/UploadProductRelations.vue
- modules/@ergonode/products/src/components/Modals/AddProductRelationsModalGrid.vue
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridProductRelationEditCell.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/ui/src/components/Grid/Grid.vue
> Remove attach column and notify with number of selected product relations

- modules/@ergonode/core/src/defaults/grid/index.js
- modules/@ergonode/core/src/models/mappers/__tests__/gridDataMapper.test.js
- modules/@ergonode/core/src/models/mappers/gridDataMapper.js
- modules/@ergonode/core/src/services/grid/postGridData.service.js
- modules/@ergonode/products/src/components/Buttons/AddProductRelationsButton.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
- modules/@ergonode/products/src/components/Modals/AddProductRelationsModalGrid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Data/Filter/GridFilterDataCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridDateEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridDateTimeEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridMultiSelectEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridNumericEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridSelectEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridTextEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridDraggableDataColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
… data mapper
- Added support for new `products/grid` endpoint.
- Added missing unit tests for mapping grid data
Issue #900
> Add support for new grid endpoint

- cypress/integration/11:workflow/transitions/1:create.feature
- cypress/integration/11:workflow/transitions/1:create/index.test.js
- cypress/integration/11:workflow/transitions/2:read.feature
- cypress/integration/11:workflow/transitions/2:read/index.test.js
- cypress/integration/11:workflow/transitions/3:update.feature
- cypress/integration/11:workflow/transitions/3:update/index.test.js
- cypress/integration/11:workflow/transitions/4:delete.feature
- cypress/integration/11:workflow/transitions/4:delete/index.test.js
- cypress/integration/common/actions.test.js
- modules/@ergonode/roles/src/extends/transition/components/Forms/TransitionFormRole.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionFab.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTransitionFab.vue
- modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutElement.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowTransitionForm.vue
- modules/@ergonode/workflow/src/pages/workflow/index.vue
e2e tests for transition 
Issue #882 
> e2e transition test

- modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
Removing an attribute from a batch action clears its values anyway
Issue #903 
> bugfix: remove attribute from btach action

- modules/@ergonode/core/src/models/__tests__/arrayWrapper.test.js
- modules/@ergonode/core/src/models/arrayWrapper.js
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
In the relationship attribute, when trying to drag an empty cell, we get errors.
> bugfix: product relation cell- remove

- modules/@ergonode/conditions/src/services/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
Remove condition set delete request.
Issue #906 
> bugfix: remove condtion set delete reqiest

- modules/@ergonode/segments/src/store/segment/actions.js
- modules/@ergonode/status-transitions/src/store/statusTransition/actions.js
Remove condition set delete request.
Issue #906 
> bugfix: remove condition set delete request

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/core/src/defaults/grid/index.js
- modules/@ergonode/core/src/models/mappers/__tests__/sideBarDataMapper.test.js
- modules/@ergonode/core/src/models/mappers/sideBarDataMapper.js
- modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/products/src/components/AdvancedFilters/ProductAdvancedFilters.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/products/src/components/Modals/AddProductRelationsModalGrid.vue
- modules/@ergonode/products/src/components/Placeholders/ProductsGridNoDataPlaceholder.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Header/GridHeaderCell.vue
- modules/@ergonode/ui/src/components/Modal/ModalGrid.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
- modules/@ergonode/ui/src/components/TabBar/VerticalTabBarList.vue
- modules/@ergonode/ui/src/components/TabBar/VerticalTabContent.vue
- Added possibility of filtering products relations by system attributes and attributes
Issue #900 
> Add advanced filters to product relations grid

- modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
removes attributes without checking the language and when an attribute is in more than one language removes all attributes
Issue #903 
> bugfix: remove attributes without checking language

- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
- modules/@ergonode/products/src/extends/components/Grids/ProductVariantsToAttachGrid.vue
- modules/@ergonode/products/src/extends/components/Grids/ProductsToAttachForGroupGrid.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
Remove action column from batch actions
Issue #915 
> bugfix: remove action column

- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionCellActionsPanel.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionDefaultCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/Header/GridSelectCollectionHeaderCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
> Add support for selecting / editing / removing cells in GridCollectionLayout

- .github/workflows/e2e.yml
- cypress.json
- package-lock.json
- package.json
> tests: E2E tests on GitHub Actions

- modules/@ergonode/notifications/src/components/NotificationList/Item/NotificationListItemTemplate.vue
- modules/@ergonode/product-batch-actions/src/components/NotificationLists/Items/NotificationListBatchActionEndedItem.vue
- modules/@ergonode/ui/src/components/Badges/RoundedBadge.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/Resizer/GridColumnResizer.vue
- modules/@ergonode/ui/src/components/List/ListElement.vue
- modules/@ergonode/ui/src/components/List/ListElementDescription.vue
- modules/@ergonode/ui/src/components/Resizer/Resizer.vue
- modules/@ergonode/ui/src/components/SideBar/SideBar.vue
- modules/@ergonode/ui/src/components/TabBar/VerticalTabContent.vue
- modules/@ergonode/ui/src/components/TreeAccordion/TreeAccordionItem.vue
- package-lock.json
- package.json
Add horizontal resizing to vertical tabbar component
> Resizing vertical tabbar

- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
> Add missing import dispatch

- modules/@ergonode/channels/src/components/Forms/SchedulerForm.vue
Add missing `Start tim`e field validation and fix error while clearing value in `Start time` field.
Issue #928 
> bugfix: Start time filed validation

- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeGalleryFormField.vue
- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeImageFormField.vue
- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeProductRelationFormField.vue
- modules/@ergonode/products/src/components/Buttons/AddProductRelationsButton.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
Include selected product relations into validation
Issue #900
> Include selected product relations in validation

- modules/@ergonode/products/src/components/Buttons/AddProductRelationsButton.vue
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
Include already chosen values to validations
Issue #900
> Improve product relation validations

- modules/@ergonode/attribute-groups/src/components/Modals/CreateAttributeGroupModalForm.vue
- modules/@ergonode/attributes/src/components/Modals/CreateAttributeModalForm.vue
- modules/@ergonode/categories/src/components/Modals/CreateCategoryModalForm.vue
- modules/@ergonode/category-trees/src/components/Modals/CreateCategoryTreeModalForm.vue
- modules/@ergonode/channels/src/components/Modals/CreateChannelModalForm.vue
- modules/@ergonode/collections/src/components/Modals/CreateCollectionModalForm.vue
- modules/@ergonode/core/src/components/Modals/CreateUnitModalForm.vue
- modules/@ergonode/core/src/mixins/route/beforeRouteLeaveMixin.js
- modules/@ergonode/import/src/components/Modals/CreateImportProfileModalForm.vue
- modules/@ergonode/product-statuses/src/components/Modals/CreateProductStatusModalForm.vue
- modules/@ergonode/product-templates/src/components/Modals/CreateProductTemplateModalForm.vue
- modules/@ergonode/products/src/components/Modals/CreateProductModalForm.vue
- modules/@ergonode/roles/src/components/Modals/CreateRoleModalForm.vue
- modules/@ergonode/segments/src/components/Modals/CreateSegmentModalForm.vue
- modules/@ergonode/status-transitions/src/components/Modals/CreateStatusTransitionModalForm.vue
- modules/@ergonode/users/src/components/Modals/CreateUserModalForm.vue
- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowStatusButton.vue
- modules/@ergonode/workflow/src/components/Modals/CreateWorkflowStatusModalForm.vue
> Add missing clearing state to create modals

- modules/@ergonode/collections/src/components/Modals/AddProductsBySKUModalForm.vue
- modules/@ergonode/collections/src/components/Modals/AddProductsFromSegmentModalForm.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsBySKUModalForm.vue
- modules/@ergonode/products/src/extends/components/Modals/AddProductsFromSegmentModalForm.vue
Adding product by collection and segment was missing clearing vuex state methods 
Issue #900
> Add missing clearing state to modals

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/attributes/src/extends/attribute/components/VerticalTabs/AttributesVerticalTab.vue
- modules/@ergonode/category-trees/src/config/extends.js
- modules/@ergonode/category-trees/src/extends/product/components/VerticalTabs/CategoryTreesVerticalTab.vue
Hide adding category / attribute from sidebars in attribute product relations modal
Issue #900
> Hide adding attribute / category

- cypress/integration/common/actions.test.js
- modules/@ergonode/conditions/src/config/extends.js
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
> Resolve conflicts with master

- modules/@ergonode/core/src/components/Translation/TranslatableTitleProvider.vue
- modules/@ergonode/media/src/components/Tabs/UploadFileTab.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/AdvancedFilter.vue
- modules/@ergonode/ui/src/components/CheckBox/CheckBox.vue
- modules/@ergonode/ui/src/components/Input/InputUUIDProvider.vue
- modules/@ergonode/ui/src/components/RadioButton/RadioButton.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
- modules/@ergonode/ui/src/components/Select/Select.vue
- modules/@ergonode/ui/src/components/TextArea/TextArea.vue
- modules/@ergonode/ui/src/components/TextField/TextField.vue
- modules/@ergonode/ui/src/components/Toggler/Toggler.vue
- modules/@ergonode/ui/src/components/UploadFile/UploadFile.vue
The old approach with generating dynamic inputs id / for UUID was not working for each scenario. Radiobuttons, checboxes, switches weren't getting these values after page was refreshed. Changed approach from mixin to renderless component.
> Improve associated label for inputs

- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridProductRelationDataCell.vue
> Product relation draft highlighting

- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/ui/src/components/LazyImage/LazyImage.vue
> Loading images

- modules/@ergonode/attributes/src/extends/attribute/methods/index.js
Translations weren't mapped well - they were overwriting instead of merging when extending was happening
> Translations mapping

- modules/@ergonode/workflow/src/locales/en_GB.json
> Correct status transition translation spelling

- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
> Workflow designer left padding

- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowStatusButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionFab.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
Create status without saving changes on transitions.
Issue #882 
> bugfix: create status without save

- modules/@ergonode/dashboard/src/components/Widgets/StatusesWidget.vue
- modules/@ergonode/dashboard/src/locales/en_GB.json
- modules/@ergonode/dashboard/src/locales/pl_PL.json
Add missing translations
Issue #867
> Add missing status widget translations

- modules/@ergonode/core/src/services/grid/postGridData.service.js
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
> Product relations grid crash on column removal

- modules/@ergonode/ui/src/components/Grid/Header/GridHeader.vue
Hide table layout activator when collection layout is disabled
> Hide table layout activator

- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerEditStatusLink.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Inputs/WorkflowStatusPreview.vue
> Hover status workflow column header

- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowStatusButton.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTransitionFab.vue
- modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/WorkflowDesignerCalculations.test.js
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
Show transition edit button.
Issue #882 
> Er 1399/transitions edit button

- modules/@ergonode/core/src/defaults/grid/index.js
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
- modules/@ergonode/products/src/config/extends.js
- modules/@ergonode/products/src/config/imports.js
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Collection/Cells/GridProductAttachCollectionCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionDefaultCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Presentation/GridImagePresentationCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
- improved collection cells resposivity
- increased table row heights
> Grid layout visual improvement

- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
> Transition tooltip title

- modules/@ergonode/attributes/src/locales/pl_PL.json
- modules/@ergonode/authentication/src/locales/pl_PL.json
- modules/@ergonode/channels/src/locales/pl_PL.json
- modules/@ergonode/collections/src/locales/pl_PL.json
- modules/@ergonode/comments/src/locales/pl_PL.json
- modules/@ergonode/import/src/locales/pl_PL.json
- modules/@ergonode/product-batch-actions/src/locales/pl_PL.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/users/src/locales/pl_PL.json
> Polish interface translations

- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/ui/src/components/Grid/Grid.vue
…ded to Grid
When user added attribute with code_1 as advanced filter and did input any value, then the same filter could not be able to land as column in grid
> Include column visibility in detecting column

- modules/@ergonode/dashboard/src/components/WelcomeUser/WelcomeUser.vue
- modules/@ergonode/ui/src/components/LazyImage/LazyImage.vue
Avatar was not set at dashboard welcome page
> Missing user avatar

- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
editing a new transition results in a 404 error.
Issue #882 
> bugfix: edit transition not found

- .github/workflows/e2e.yml
- package-lock.json
- package.json
> New vuems version

- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
- nuxt.config.js
Change wrong component import for Workflow
Issue #963 
> bugfix: wrong import

- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
- nuxt.config.js
Change wrong component import for Workflow
Issue #963 
> wrong import

- .github/workflows/e2e.yml
> ci: Removing backend dev dependencies for tests

- modules/@ergonode/core/src/defaults/theme/index.js
- modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
- modules/@ergonode/ui/src/components/Tooltip/Tooltip.vue
> Tooltip component

- modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItem.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerMultiSelectItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerNoTypeItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerNumericItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerSelectItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerTextItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerUnitItemParameter.vue
- modules/@ergonode/conditions/src/locales/en_GB.json
- modules/@ergonode/conditions/src/locales/pl_PL.json
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormNoTypeField.vue
> Encapsulating condition set item parameters

- modules/@ergonode/ui/src/components/Input/InputUUIDProvider.vue
> Migrate uuid generation

- modules/@ergonode/core/src/models/stringWrapper.js
- modules/@ergonode/media/src/locales/en_GB.json
- modules/@ergonode/media/src/locales/pl_PL.json
- modules/@ergonode/media/src/store/media/actions.js
> Add translations for resource metadata

- modules/@ergonode/media/src/store/media/actions.js
> Add missing method for string transforming

- modules/@ergonode/comments/src/components/Forms/CommentsForm.vue
- modules/@ergonode/comments/src/components/List/CommentsList.vue
> Move create comment button to placeholder

- modules/@ergonode/channels/src/components/Buttons/CreateExportButton.vue
- modules/@ergonode/import/src/components/Buttons/CreateImportButton.vue
> Removed plus icon

- modules/@ergonode/products/src/extends/components/Forms/ProductAttributesBindingForm.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/ui/src/components/Form/Section/FormListSection.vue
- modules/@ergonode/ui/src/components/Tooltip/Tooltip.vue
> Add tooltip to product variant binding attributes, improve fluid positioning

- modules/@ergonode/attributes/src/extends/attribute/components/Forms/AttributeTranslationFormOptions.vue
Prevent allowing user to edit attribute options when has no access to editing in specific language
> Select / Multiselect attribute privilege restrictions

- modules/@ergonode/products/src/locales/pl_PL.json
- modules/@ergonode/ui/src/components/Tooltip/Tooltip.vue
When tooltip title was cleared, the tooltip was keeping old value.
> Destroy tooltip when title is empty

- modules/@ergonode/ui/src/components/Grid/Grid.vue
Allow adding grid columns only for `GridTableLayout`
> Show adding column dropzone only for GridTableLayout

- modules/@ergonode/collections/src/extends/product/components/Collection/ProductCollectionItem.vue
- modules/@ergonode/collections/src/extends/product/components/ExpandingCollection/ExpandingCollection.vue
- modules/@ergonode/collections/src/extends/product/components/Tabs/ProductCollectionTab.vue
> Unify product collection item

- modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
- modules/@ergonode/users/src/components/Forms/UserForm.vue
> Add searching and sorting for LanguageSelect

- modules/@ergonode/media/src/components/Forms/ResourceForm.vue
- modules/@ergonode/media/src/components/Grids/MediaGrid.vue
- modules/@ergonode/media/src/components/Inputs/FilePreview.vue
- modules/@ergonode/media/src/config/extends.js
- modules/@ergonode/media/src/config/imports.js
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridImagePreviewCollectionCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridImagePreviewDataCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Presentation/GridFilePresentationCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Columns/GridImagePreviewColumn.vue
- modules/@ergonode/media/src/store/media/actions.js
- modules/@ergonode/media/src/store/media/state.js
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/Cells/GridCollectionDefaultCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayout.vue
- File preview in grid cells
- File preview in resource
Issue #1007 
> Add support for preview file

- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
- modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerEditStatusLink.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowTransitionForm.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowDesignerTab.vue
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/WorkflowDesignerCalculations.test.js
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
- improve workflow designer header styling
- sync transitions
> Sync workflow transition models

- modules/@ergonode/category-trees/src/components/TreeDesigners/CategoryTreeDesigner.vue
- modules/@ergonode/category-trees/src/locales/en_GB.json
- modules/@ergonode/category-trees/src/locales/pl_PL.json
- modules/@ergonode/collections/src/extends/product/components/ExpandingCollection/ExpandingCollection.vue
- modules/@ergonode/core/src/components/LanguageInheritanceTreeDesigner/LanguageInheritanceTreeDesigner.vue
- modules/@ergonode/core/src/locales/en_GB.json
- modules/@ergonode/core/src/locales/pl_PL.json
- modules/@ergonode/media/src/components/Forms/ResourceForm.vue
- modules/@ergonode/media/src/components/Inputs/FilePreview.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridImagePreviewCollectionCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Presentation/GridFilePresentationCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Columns/GridImagePreviewColumn.vue
- modules/@ergonode/media/src/locales/en_GB.json
- modules/@ergonode/media/src/locales/pl_PL.json
> Add download file / img support

- modules/@ergonode/dashboard/src/config/index.js
- modules/@ergonode/workflow/src/components/Tabs/WorkflowTransitionConditionDesignerTab.vue
Remove wrong relations
Issue #1014 
> bugfix: remove workflow relations

- modules/@ergonode/media/src/components/Inputs/FilePreview.vue
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
> Downloaded resource with correct extension

- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
> Replace download resource url

- modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Collection/Cells/GridMediaAttachCollectionCell.vue
> Add missing extended image preview cells

- cypress/integration/00:auth/1:login.feature
- cypress/integration/00:auth/1:login/index.test.js
- cypress/integration/00:auth/2:help.feature
- cypress/integration/00:auth/2:help/index.test.js
- cypress/integration/00:auth/3:password.feature
- cypress/integration/00:auth/3:password/index.test.js
- modules/@ergonode/authentication/src/components/Forms/LoginCredentialsForm.vue
- modules/@ergonode/authentication/src/components/Forms/LoginForm.vue
- modules/@ergonode/authentication/src/components/Forms/LoginHelpForm.vue
- modules/@ergonode/authentication/src/components/Forms/PasswordRecoveryForm.vue
- modules/@ergonode/authentication/src/components/Layout/Login.vue
- package-lock.json
- package.json
e2e tests for auth
Issue #969 
> e2e auth tests

- jest.config.js
- modules/@ergonode/core/src/components/FlashMessages/__tests__/FlashMessage.test.js
- modules/@ergonode/core/src/components/ToolBar/__tests__/ToolBarUserButton.test.js
- modules/@ergonode/product-batch-actions/src/components/Modals/UpdateProductsModal.vue
- modules/@ergonode/product-batch-actions/src/components/VerticalTabs/AttributesVerticalTab.vue
- modules/@ergonode/products/src/components/Progress/__tests__/ProductCompleteness.test.js
- modules/@ergonode/ui/src/components/AdvancedFilters/Dropdown/AdvancedFilterDropdown.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/__tests__/AdvancedFilterShowOnly.test.js
- modules/@ergonode/ui/src/components/Alert/__tests__/Alert.test.js
- modules/@ergonode/ui/src/components/Badges/__tests__/InformationBadge.test.js
- modules/@ergonode/ui/src/components/Badges/__tests__/NumericBadge.test.js
- modules/@ergonode/ui/src/components/Badges/__tests__/PointBadge.test.js
- modules/@ergonode/ui/src/components/Designer/__tests__/Designer.test.js
- modules/@ergonode/ui/src/components/Designer/__tests__/DesignerGhostItem.test.js
- modules/@ergonode/ui/src/components/Layout/Errors/__tests__/404.test.js
- modules/@ergonode/ui/src/components/Layout/Errors/__tests__/__snapshots__/404.test.js.snap
- modules/@ergonode/ui/src/components/MenuList/__tests__/MenuListElement.test.js
- modules/@ergonode/ui/src/components/Resizer/Resizer.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
- modules/@ergonode/ui/src/components/TitleBar/__tests__/TitleBar.test.js
- modules/@ergonode/ui/src/components/TitleBar/__tests__/TitleBarBreadcrumb.test.js
- modules/@ergonode/ui/src/components/TitleBar/__tests__/__snapshots__/TitleBar.test.js.snap
- modules/@ergonode/ui/src/components/TitleBar/__tests__/__snapshots__/TitleBarBreadcrumb.test.js.snap
- modules/@ergonode/ui/src/components/ToolBar/__tests__/ToolBarSelectButton.test.js
Product batch actions - pulling the same attributes
Fix unit test errors
Fix linter warings. 
Issue #1021
> Er 1460/batch actions sidebar

- modules/@ergonode/conditions/src/components/TreeDesigners/ConditionSetTreeDesignerItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerMultiSelectItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerNumericItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerSelectItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerTextItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerUnitItemParameter.vue
- modules/@ergonode/conditions/src/models/conditionSetMapper.js
Condition type item parameters weren't have passed affected by values 
> Add missing affected by values

- modules/@ergonode/ui/src/components/Observers/IntersectionObserver.vue
- modules/@ergonode/ui/src/components/ToolBar/ToolBarSelectButton.vue
Add default threshold value to be called instantly when element will appear at the view port
> Default intersection observer threshold

- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
> Improve grid rendering order

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/attributes/src/extends/attribute/components/SideBars/AttributeSideBarElement.vue
- modules/@ergonode/attributes/src/locales/en_GB.json
- modules/@ergonode/attributes/src/locales/pl_PL.json
- modules/@ergonode/core/src/store/dictionaries/actions.js
- modules/@ergonode/product-templates/src/components/SideBars/WidgetSideBarElement.vue
- modules/@ergonode/product-templates/src/components/TemplateDesigner/ProductDesigner/AttributeElementContent.vue
- modules/@ergonode/product-templates/src/components/TemplateDesigner/ProductDesigner/SectionElementContent.vue
- modules/@ergonode/product-templates/src/locales/en_GB.json
- modules/@ergonode/product-templates/src/locales/pl_PL.json
- modules/@ergonode/product-templates/src/pages/product-templates/_template/_id.vue
Attribute type translations
Improving styles in the category tree
Issues: #1028 
> attribute types translations

- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- Change `index` to `esa_index` 
- Change `sku` to `esa_sku`
> Rename default product columns

- cypress/integration/common/inputs.test.js
- cypress/support/commands.js
- modules/@ergonode/attributes/src/locales/en_GB.json
- modules/@ergonode/ui/src/components/Select/Select.vue
- package-lock.json
- package.json
> Improve select option e2e, update cypress version

- modules/@ergonode/ui/src/components/Designer/DesignerItem.vue
- modules/@ergonode/ui/src/components/Designer/DesignerItemDescription.vue
- modules/@ergonode/ui/src/components/TreeDesigner/TreeDesignerItem.vue
Change menu position on category tree items.
Set tooltip on item title.
Issue #1028 
> change menu position on tree item

- CHANGELOG.md
- modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterDateContent.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateType.vue
> Fixed an empty record for advanced date type filter

- CHANGELOG.md
- modules/@ergonode/ui/src/components/UploadFileList/UploadFileListElement.vue
> Fixed too long filename for uploaded resource

- CHANGELOG.md
- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadImageFile.vue
- modules/@ergonode/media/src/config/extends.js
- modules/@ergonode/media/src/config/imports.js
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Data/GridImagePreviewDataCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridGalleryEditCell.vue
- modules/@ergonode/media/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridImagePreviewEditCell.vue
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Content/GridImageEditContentCell.vue
- modules/@ergonode/ui/src/components/Input/InputSolidStyle.vue
> Allow preview resource cell from media grid

- modules/@ergonode/attribute-groups/src/components/Autocompletes/AttributeGroupsAutocomplete.vue
- modules/@ergonode/attributes/src/components/Autocompletes/AttributesAutocomplete.vue
- modules/@ergonode/collections/src/components/Autocompletes/CollectionTypesAutocomplete.vue
- modules/@ergonode/product-templates/src/components/Autocompletes/ProductTemplatesAutocomplete.vue
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
- modules/@ergonode/roles/src/components/Autocompletes/RolesAutocomplete.vue
- modules/@ergonode/segments/src/components/Autocompletes/SegmentsAutocomplete.vue
- modules/@ergonode/ui/src/components/Autocomplete/Autocomplete.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridMultiSelectEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridMultiSelectEditCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridSelectEditCell.vue
- modules/@ergonode/ui/src/components/Input/InputSelectValue.vue
- modules/@ergonode/ui/src/components/Input/InputUnderlineStyle.vue
- modules/@ergonode/ui/src/components/Select/Select.vue
> Add wrap value option to select input kind

- cypress/integration/05:template/1:create.feature
- cypress/integration/05:template/2:read.feature
- cypress/integration/05:template/3:update.feature
- cypress/integration/05:template/4:delete.feature
- cypress/integration/common/navigation.test.js
- modules/@ergonode/product-templates/src/components/Forms/ProductTemplateForm.vue
- modules/@ergonode/product-templates/src/locales/en_GB.json
- modules/@ergonode/product-templates/src/locales/pl_PL.json
- modules/@ergonode/product-templates/src/store/productTemplate/actions.js
- modules/@ergonode/product-templates/src/store/productTemplate/state.js
- modules/@ergonode/ui/src/components/Form/Form.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridRowActionColumn.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/ui/src/components/RichTextEditor/Button/RichTextEditorActionIconButton.vue
- modules/@ergonode/ui/src/components/RichTextEditor/Menu/RichTextEditorMenu.vue
Add support for template code
- [ x I have added tests that prove my fix is effective or that my feature works
> Add support for template code

- modules/@ergonode/products/src/extends/components/Forms/ProductAttributesBindingForm.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
> Add paragraph info to attribute bindings

- modules/@ergonode/media/src/components/Grids/AddMediaGrid.vue
> Add missing extension column to media grid

- modules/@ergonode/batch-actions/src/config/extends.js
- modules/@ergonode/batch-actions/src/locales/en_GB.json
- modules/@ergonode/batch-actions/src/locales/pl_PL.json
- modules/@ergonode/product-batch-actions/src/components/NotificationLists/Items/NotificationListBatchActionsProcessingItem.vue
- modules/@ergonode/product-batch-actions/src/config/extends.js
- modules/@ergonode/product-batch-actions/src/config/imports.js
- modules/@ergonode/ui/src/components/Modal/ModalHeader.vue
> Add support for extending batch action processing section items

- modules/@ergonode/notifications/src/components/Badges/NotificationWarningBadge/NotificationWarningBadge.vue
- modules/@ergonode/notifications/src/components/ToolBar/ToolBarNotificationButton.vue
- modules/@ergonode/notifications/src/store/notification/state.js
> Add warning icon to notification Toolbar button

- modules/@ergonode/batch-actions/src/config/extends.js
- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/notifications/src/components/NotificationList/NotificationList.vue
- modules/@ergonode/notifications/src/defaults/index.js
- modules/@ergonode/notifications/src/store/notification/__tests__/index.test.js
- modules/@ergonode/notifications/src/store/notification/actions.js
- modules/@ergonode/notifications/src/store/notification/state.js
> Integrate batch actions with notifications check mechanism

- modules/@ergonode/batch-actions/src/config/extends.js
- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/ui/src/components/ProgressBar/Circle/CircleProgressBar.vue
> Get batch action by id and end batch action endpoint

- modules/@ergonode/batch-actions/src/services/index.js
> Add reprocessing batch action

- modules/@ergonode/batch-actions/src/services/index.js
- modules/@ergonode/notifications/src/components/Badges/NotificationWarningBadge/NotificationWarningBadge.vue
- modules/@ergonode/notifications/src/components/ToolBar/ToolBarNotificationButton.vue
- modules/@ergonode/ui/src/components/ProgressBar/Circle/CircleProgressBar.vue
> Add payload to reprocessing batch action

- modules/@ergonode/categories/src/components/Selects/CategorySelect.vue
- modules/@ergonode/category-trees/src/components/AdvancedFilters/Type/AdvancedFilterCategoryTreeType.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerMultiSelectItemParameter.vue
- modules/@ergonode/conditions/src/components/TreeDesigners/ItemParameters/ConditionSetTreeDesignerSelectItemParameter.vue
- modules/@ergonode/core/src/components/Selects/LanguageSelect.vue
- modules/@ergonode/core/src/components/Selects/LanguageTreeSelect.vue
- modules/@ergonode/core/src/models/mappers/translationsMapper.js
- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeMultiSelectFormField.vue
- modules/@ergonode/product-batch-actions/src/components/Forms/Fields/AttributeSelectFormField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormMultiSelectField.vue
- modules/@ergonode/products/src/components/Forms/Field/ProductTemplateFormSelectField.vue
- modules/@ergonode/products/src/extends/components/Forms/Field/ProductAttributeBindingField.vue
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
- modules/@ergonode/status-transitions/src/components/Forms/TransitionForm.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterMultiselectContent.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterSelectContent.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridMultiSelectEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/Filter/GridSelectEditFilterCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridMultiSelectEditCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridSelectEditCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
- modules/@ergonode/ui/src/components/Select/Select.vue
- modules/@ergonode/ui/src/components/Select/TranslationSelect.vue
- modules/@ergonode/ui/src/components/SelectList/SelectList.vue
- modules/@ergonode/ui/src/components/SelectList/SelectListElement.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowTransitionForm.vue
> Add support for complex options

- modules/@ergonode/core/src/defaults/grid/index.js
- modules/@ergonode/ui/src/components/Grid/Grid.vue
- modules/@ergonode/ui/src/components/Grid/Header/GridHeader.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Collection/GridCollectionLayoutActivator.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayoutActivator.vue
- modules/@ergonode/ui/src/components/Grid/Modals/GridSettingsModalForm.vue
> Allow defining custom layouts for Grid component

- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
Extend product grid about custom layout slot.
Issue #1069 
> extend custom layout

- modules/@ergonode/ui/src/components/Grid/Grid.vue
Add layout key to URL address.
Issue #1075 
> add layout to url

- modules/@ergonode/dashboard/src/config/index.js
- modules/@ergonode/workflow/src/components/Tabs/WorkflowTransitionConditionDesignerTab.vue
> bugfix: remove workflow relations (#1015)

- modules/@ergonode/category-trees/src/components/AdvancedFilters/Type/AdvancedFilterCategoryTreeType.vue
- modules/@ergonode/dashboard/src/pages/dashboard/index.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterMultiselectContent.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Content/AdvancedFilterSelectContent.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterMultiSelectType.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterNumericType.vue
- modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterSelectType.vue
- modules/@ergonode/ui/src/components/CheckBox/CheckBox.vue
- modules/@ergonode/ui/src/components/ExpandingList/ExpandingList.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/GridTableLayout.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/Dropdown.vue
- modules/@ergonode/ui/src/components/Select/Dropdown/SelectDropdown.vue
- modules/@ergonode/ui/src/components/Select/Select.vue
- modules/@ergonode/ui/src/components/SelectList/SelectList.vue
- modules/@ergonode/ui/src/components/SelectList/SelectListElement.vue
- modules/@ergonode/ui/src/components/TreeAccordion/TreeAccordion.vue
- modules/@ergonode/ui/src/plugins/global-component-loader.js
- package-lock.json
- package.json
> Change DOM virtualization for dropdown lists

- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
Attribute options sorting. Replace option component to drag&drop option component.
Issue #1113 
> feature(attribute): sort attribute options

- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
> Request product completeness on language change

- modules/@ergonode/attributes/src/extends/attribute/methods/index.js
- modules/@ergonode/products/src/components/Grids/AddProductRelationsGrid.vue
> Error attribute option mapping

- modules/@ergonode/attributes/src/extends/attribute/methods/index.js
> Fix attribute option keys validation

- modules/@ergonode/products/src/components/Progress/ProductCompleteness.vue
- modules/@ergonode/products/src/components/Tabs/ProductTemplateTab.vue
> Product completeness on language change

- modules/@ergonode/ui/src/components/ExpandingList/ExpandingList.vue
- modules/@ergonode/ui/src/components/SideBar/SideBar.vue
> Change Sidebar DOM virtualization

- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Resizer/GridCellResizer.vue
- modules/@ergonode/ui/src/mixins/grid/gridResizerCellMixin.js
> Add scrollTop to resizing algorithm

- modules/@ergonode/media/src/components/Inputs/UploadFile/UploadFiles.vue
- modules/@ergonode/ui/src/components/List/ListLinkElement.vue
- modules/@ergonode/ui/src/plugins/global-component-loader.js
Add **ListLinkElement** component which wrap the **ListElement** with **NuxtLink**. Apply it for **UploadFiles** component which will allow user to navigate to the resource.
Issue #1126 
> Add ListLinkElement component

- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValue.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValues.vue
- modules/@ergonode/attributes/src/extends/attribute/store/actions.js
> Add missing updating option translation logic

- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridNumericEditCell.vue
- modules/@ergonode/ui/src/components/Grid/Layout/Table/Cells/Edit/GridTextEditCell.vue
- modules/@ergonode/ui/src/components/Paragraph/Paragraph.vue
- modules/@ergonode/ui/src/components/RichTextEditor/RichTextEditor.vue
> Add preview for text, numeric and rte grid editable cells

- modules/@ergonode/products/src/components/Inputs/UploadProductRelations.vue
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/products/src/locales/pl_PL.json
> feat(core): Add remove all relations option

- modules/@ergonode/channels/src/components/Forms/ChannelForm.vue
- modules/@ergonode/core/src/models/mappers/errorsMapper.js
- modules/@ergonode/import/src/components/Forms/ImportProfileForm.vue
- modules/@ergonode/product-templates/src/components/SideBars/WidgetsSideBar.vue
- modules/@ergonode/ui/src/components/ExpandingList/ExpandingList.vue
- modules/@ergonode/ui/src/components/Form/Form.vue
- modules/@ergonode/ui/src/components/SideBar/SideBar.vue
> Add import / channel form errors mappers

- modules/@ergonode/core/src/plugins/core.js
- modules/@ergonode/product-batch-actions/src/config/extends.js
- modules/@ergonode/products/src/components/Grids/ProductsGrid.vue
> Allow extended slots to be defined by layout

- modules/@ergonode/core/src/models/mappers/translationsMapper.js
- modules/@ergonode/ui/src/components/AdvancedFilters/Type/AdvancedFilterDateTimeType.vue
> Filter mapping

- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormGhostItem.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
> Keeping track of drag end for draggable form item

- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
> Simplifying manipulating draggable item form

- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
> Mutate item position on drag end

- UPGRADE-1.3.md
- cypress/integration/11:workflow/transitions/2:read.feature
- cypress/integration/11:workflow/transitions/4:delete.feature
- modules/@ergonode/products/src/locales/en_GB.json
- modules/@ergonode/status-transitions/src/components/Forms/TransitionForm.vue
- modules/@ergonode/status-transitions/src/components/Modals/CreateStatusTransitionModalForm.vue
- modules/@ergonode/status-transitions/src/pages/status-transitions/_transition/_id.vue
- modules/@ergonode/status-transitions/src/services/index.js
- modules/@ergonode/status-transitions/src/store/statusTransition/actions.js
- modules/@ergonode/status-transitions/src/store/statusTransition/state.js
- modules/@ergonode/ui/src/components/Alert/Alert.vue
- modules/@ergonode/ui/src/components/Paragraph/Paragraph.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowTransitionForm.vue
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
- modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
- modules/@ergonode/workflow/src/services/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
- modules/@ergonode/workflow/src/store/workflow/state.js
Breaking changes are described in `UPGRADE-1.3.md`
Issue #1144 
> Transition property naming

- CHANGELOG.md
- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/category-trees/src/config/extends.js
> Remove defined layouts

- CHANGELOG.md
- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/category-trees/src/config/extends.js
> Sync transition naming with master

- modules/@ergonode/attributes/src/extends/attribute/methods/index.js
> feat(core): Prevent removing not added option

- .github/workflows/e2e.yml
- .github/workflows/tests.yaml
> Sync master to feature

- UPGRADE-1.3.md
- cypress/integration/11:workflow/status/1:create.feature
- cypress/integration/11:workflow/status/2:read.feature
- cypress/integration/11:workflow/status/3:update.feature
- cypress/integration/11:workflow/status/4:delete.feature
- cypress/integration/11:workflow/transitions/1:create.feature
- cypress/integration/11:workflow/transitions/2:read.feature
- cypress/integration/11:workflow/transitions/3:update.feature
- cypress/integration/11:workflow/transitions/4:delete.feature
- modules/@ergonode/workflow/src/components/Buttons/CreateWorkflowTransitionsButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTransitionConditionDesignerButton.vue
- modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutArrowActions.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowTransitionGeneralTab.vue
- modules/@ergonode/workflow/src/config/routes.js
- modules/@ergonode/workflow/src/pages/workflow/_status/_id.vue
- modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
- modules/@ergonode/workflow/src/services/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
- package-lock.json
- package.json
You need to redesign routing structure in workflow to support workflow id.
In this task, you will need to adjust the routing assembly mechanism so that you can write routing from within the extension.
install new VueMS version. 
Issue #1155
> Er 1885/workflow routing change

- modules/@ergonode/core/src/components/LanguageInheritanceTreeDesigner/LanguageInheritanceTreeDesigner.vue
- modules/@ergonode/core/src/components/LanguageInheritanceTreeDesigner/LanguageInheritanceTreeDesignerItem.vue
- modules/@ergonode/roles/src/config/extends.js
- modules/@ergonode/roles/src/config/imports.js
- modules/@ergonode/roles/src/extends/workflow/components/Forms/WorkflowTransitionFormRole.vue
- modules/@ergonode/roles/src/extends/workflow/methods/index.js
- modules/@ergonode/roles/src/extends/workflow/store/index.js
- modules/@ergonode/roles/src/extends/workflow/store/state.js
- modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
Extends language items on settings.
Bug fix in workflow during statuses landing  
fix bug in role module, when expanding transitions form
Issue #1159
> Er 1883/extend settings

- modules/@ergonode/products/src/components/Buttons/ProductWorkflowActionButton.vue
> Display code when translation not defined

- modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
- modules/@ergonode/workflow/src/store/workflow/actions.js
- modules/@ergonode/workflow/src/store/workflow/state.js
when updating workflow information you need to add "code" and "default_id" fields
Issue #1155 
> Er 1881/update workflow

- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerDraggableHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
> feat(workflow): Add dragstart for status header

- .github/workflows/e2e.yml
- .github/workflows/tests.yaml
GitHub Action constant node version
Issue #1165 
> set const node version

- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowStatusButton.vue
- modules/@ergonode/workflow/src/components/Buttons/RemoveWorkflowTransitionButton.vue
- modules/@ergonode/workflow/src/pages/workflow/_transition/_id.vue
- modules/@ergonode/workflow/src/store/workflow/actions.js
incorrect fetching data for default status id.
Change target routing when removing status and transition.
Issue #1155 
> bugfix: status default id

- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
Refresh workflow designer when new status is added.
Issue #1155 
> bugfix: refresh workflow when add status

- modules/@ergonode/attributes/src/config/extends.js
- modules/@ergonode/attributes/src/defaults/index.js
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValue.vue
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionValues.vue
- modules/@ergonode/attributes/src/extends/attribute/methods/helpers.js
- modules/@ergonode/attributes/src/extends/attribute/methods/index.js
- modules/@ergonode/attributes/src/extends/attribute/services/index.js
- modules/@ergonode/attributes/src/extends/attribute/store/actions.js
- modules/@ergonode/attributes/src/extends/attribute/store/mutations.js
- modules/@ergonode/attributes/src/extends/attribute/store/state.js
- modules/@ergonode/attributes/src/services/index.js
- modules/@ergonode/core/src/models/__tests__/arrayWrapper.test.js
- modules/@ergonode/core/src/models/arrayWrapper.js
- modules/@ergonode/products/src/components/Buttons/ProductWorkflowActionButton.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableForm.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormGhostItem.vue
- modules/@ergonode/ui/src/components/DraggableForm/DraggableFormItem.vue
- modules/@ergonode/ui/src/components/Form/Section/FormListSection.vue
Merge master to feature branch
> Workflow part1 master

- cypress/integration/03:category/3:update.feature
- cypress/integration/13:media/1:upload/index.test.js
- modules/@ergonode/attributes/src/extends/attribute/components/Forms/Sections/AttributeOptionKeyValues.vue
- modules/@ergonode/ui/src/components/Autocomplete/Autocomplete.vue
> bugfix: fix e2e tests

- modules/@ergonode/ui/src/components/NavigationSideBar/NavigationSideBarElement.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- workflow menu selection
- default status, refresh designer statuses
> bugfix: workflow menu fix

- CHANGELOG.md
- cypress/integration/01:attributeGroups/3:update.feature
- cypress/integration/13:media/1:upload/index.test.js
> Attribute group e2e fix

- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/models/workflowDesigner/__tests__/__mocks__/index.js
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
Remove the wrong field sending to backend workflow end-point. 
Issue #1179 
> bugfix(workflow): extra field remove

- modules/@ergonode/product-statuses/src/pages/product-statuses/_status/_id.vue
- modules/@ergonode/product-statuses/src/services/index.js
- modules/@ergonode/product-statuses/src/store/productStatus/actions.js
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Forms/WorkflowStatusForm.vue
- modules/@ergonode/workflow/src/config/routes.js
- modules/@ergonode/workflow/src/pages/workflow/_status/_id.vue
- modules/@ergonode/workflow/src/store/workflow/actions.js
Fetch default status information from wrong place.
Issue #1179 
> bugfix(workflow): default status fetch from workflow

- modules/@ergonode/workflow/src/components/Buttons/UpdateWorkflowTranslationButton.vue
- modules/@ergonode/workflow/src/components/Inputs/WorkflowStatusPreview.vue
- modules/@ergonode/workflow/src/components/Modals/CreateWorkflowStatusModalForm.vue
- modules/@ergonode/workflow/src/components/Tabs/WorkflowStatusGeneralTab.vue
- modules/@ergonode/workflow/src/locales/en_GB.json
- modules/@ergonode/workflow/src/locales/pl_PL.json
- modules/@ergonode/workflow/src/store/workflow/actions.js
- get default status from workflow context
- add translations
Issue #1179 
> bugfix: get default status from workflow

- modules/@ergonode/workflow/src/components/Designers/VirtualOverlay/WorkflowDesignerVirtualOverlay.vue
- modules/@ergonode/workflow/src/components/Designers/VirtualOverlay/WorkflowDesignerVirtualOverlayColumn.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerDraggableColumnLayer.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerDraggableHeaderLayerCell.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerHeaderLayerCell.vue
Add drag & drop layer on header and virtual overlay.
Issue #1167 
> Er 1890/drag and drop column

- modules/@ergonode/ui/src/components/Grid/Layout/Table/Columns/GridDraggableColumn.vue
- modules/@ergonode/ui/src/models/dragAndDrop/getColumnsTransforms.js
- modules/@ergonode/workflow/src/components/Designers/VirtualOverlay/WorkflowDesignerVirtualOverlay.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesignerDraggableColumnLayer.vue
- modules/@ergonode/workflow/src/services/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
Change drag&drop mechanism to css transition. 
Connect with API and save status order.
Issue #1167 
> Er 1896/rebuild status array

- modules/@ergonode/workflow/src/components/Designers/LayoutElements/WorkflowDesignerLayoutElement.vue
- modules/@ergonode/workflow/src/components/Designers/WorkflowDesigner.vue
- modules/@ergonode/workflow/src/models/workflowDesigner/index.js
- modules/@ergonode/workflow/src/store/workflow/actions.js
Rebuild transitions when d&d statuses.
Issue #1167 
> feature: transition rebuild when d&d

- CHANGELOG.md
- modules/@ergonode/products/src/extends/ui/components/Grid/Layout/Table/Cells/Edit/GridLabelEditCell.vue
- modules/@ergonode/products/src/services/index.js
Incorrect status column translation
Issue #1196 
> bugfix: incorrect status translation

- modules/@ergonode/products/src/components/Tabs/ProductCatalogTab.vue
Product filter by category does not work correctly. 
> bugfix: category filter

- lerna.json
- modules/@ergonode/activity-logs/package.json
- modules/@ergonode/attribute-groups/package.json
- modules/@ergonode/attributes/package.json
- modules/@ergonode/authentication/package.json
- modules/@ergonode/batch-actions/package.json
- modules/@ergonode/categories/package.json
- modules/@ergonode/category-trees/package.json
- modules/@ergonode/channels/package.json
- modules/@ergonode/collections/package.json
- modules/@ergonode/comments/package.json
- modules/@ergonode/conditions/package.json
- modules/@ergonode/core/package.json
- modules/@ergonode/dashboard/package.json
- modules/@ergonode/import/package.json
- modules/@ergonode/media/package.json
- modules/@ergonode/notifications/package.json
- modules/@ergonode/product-batch-actions/package.json
- modules/@ergonode/product-statuses/package.json
- modules/@ergonode/product-templates/package.json
- modules/@ergonode/products-comments/package.json
- modules/@ergonode/products/package.json
- modules/@ergonode/roles/package.json
- modules/@ergonode/segments/package.json
- modules/@ergonode/status-transitions/package.json
- modules/@ergonode/ui/package.json
- modules/@ergonode/users/package.json
- modules/@ergonode/workflow/package.json
- package-lock.json
- package.json
> chore(release): v1.3.0
